"""Pure-Python finance functions used by analyze.py.

No openpyxl, no Excel, no external deps beyond the standard library.
Every function is deterministic and side-effect-free so the analysis
report can be regenerated by re-running analyze.py against the CSVs
in ../value-model/.

Conventions:
- All cash flows in $M unless explicitly noted
- WACC, terminal growth, tax rates as decimals (0.121 not 12.1)
- Mid-year discount convention by default
"""
from __future__ import annotations

from dataclasses import dataclass
from statistics import median
from typing import Iterable


# ---------------------------------------------------------------------------
# DCF
# ---------------------------------------------------------------------------

@dataclass
class DCFResult:
    sum_pv_fcfs: float
    pv_terminal: float
    enterprise_value: float
    equity_value: float
    terminal_value_undiscounted: float
    terminal_pct_of_ev: float
    pv_fcfs: list[float]
    discount_factors: list[float]


def dcf(
    fcfs: list[float],
    wacc: float,
    terminal_growth: float,
    *,
    net_debt: float = 0.0,
    mid_year: bool = True,
) -> DCFResult:
    """Standard Gordon-growth DCF with mid-year convention.

    Args:
        fcfs: list of unlevered free cash flows by projection year.
        wacc: discount rate (decimal).
        terminal_growth: perpetuity growth rate (decimal); must be < wacc.
        net_debt: subtracted from enterprise value to get equity value.
        mid_year: if True, discount periods are 0.5, 1.5, ...; else 1, 2, ...
    """
    if terminal_growth >= wacc:
        raise ValueError(
            f"terminal_growth ({terminal_growth}) must be < wacc ({wacc}) "
            "to avoid infinite terminal value"
        )
    n = len(fcfs)
    periods = [(i + (0.5 if mid_year else 1.0)) for i in range(n)]
    discount_factors = [1.0 / (1.0 + wacc) ** p for p in periods]
    pv_fcfs = [f * df for f, df in zip(fcfs, discount_factors)]
    sum_pv = sum(pv_fcfs)

    final_fcf = fcfs[-1]
    tv = final_fcf * (1 + terminal_growth) / (wacc - terminal_growth)
    pv_tv = tv * discount_factors[-1]
    ev = sum_pv + pv_tv
    return DCFResult(
        sum_pv_fcfs=sum_pv,
        pv_terminal=pv_tv,
        enterprise_value=ev,
        equity_value=ev - net_debt,
        terminal_value_undiscounted=tv,
        terminal_pct_of_ev=pv_tv / ev if ev else float("nan"),
        pv_fcfs=pv_fcfs,
        discount_factors=discount_factors,
    )


def wacc_sensitivity(
    fcfs: list[float],
    wacc_axis: list[float],
    g_axis: list[float],
    *,
    net_debt: float = 0.0,
    mid_year: bool = True,
) -> list[list[float]]:
    """Build a WACC × terminal-growth sensitivity grid of equity values."""
    grid = []
    for w in wacc_axis:
        row = []
        for g in g_axis:
            try:
                row.append(dcf(fcfs, w, g, net_debt=net_debt, mid_year=mid_year).equity_value)
            except ValueError:
                row.append(float("nan"))
        grid.append(row)
    return grid


# ---------------------------------------------------------------------------
# WACC build (CAPM)
# ---------------------------------------------------------------------------

def capm_cost_of_equity(rf: float, beta: float, erp: float) -> float:
    return rf + beta * erp


def wacc(
    cost_of_equity: float,
    *,
    cost_of_debt_pretax: float = 0.0,
    tax_rate: float = 0.21,
    debt_weight: float = 0.0,
) -> float:
    after_tax_kd = cost_of_debt_pretax * (1 - tax_rate)
    equity_weight = 1.0 - debt_weight
    return cost_of_equity * equity_weight + after_tax_kd * debt_weight


# ---------------------------------------------------------------------------
# Comps
# ---------------------------------------------------------------------------

def median_multiple(comp_rows: list[dict], multiple_field: str) -> float:
    vals = []
    for row in comp_rows:
        v = row.get(multiple_field, "")
        if v in ("", "n/a", "negative", None):
            continue
        try:
            vals.append(float(v))
        except ValueError:
            continue
    if not vals:
        raise ValueError(f"No usable values for {multiple_field}")
    return median(vals)


def implied_valuation(arr: float, multiple: float) -> float:
    return arr * multiple


# ---------------------------------------------------------------------------
# Probability-weighted return analysis
# ---------------------------------------------------------------------------

@dataclass
class Outcome:
    name: str
    probability: float
    exit_value_usd_m: float


def expected_value(outcomes: Iterable[Outcome], *, ownership_pct: float) -> dict:
    outcomes = list(outcomes)
    total_p = sum(o.probability for o in outcomes)
    if abs(total_p - 1.0) > 1e-6:
        raise ValueError(f"Probabilities must sum to 1.0; got {total_p}")
    ev = 0.0
    for o in outcomes:
        ev += o.probability * o.exit_value_usd_m * ownership_pct
    return {"ev_usd_m": ev, "outcomes": outcomes}


def irr_5y_from_multiple(initial_check_usd_m: float, exit_usd_m: float) -> float:
    """Compute 5-year IRR for a fixed exit value."""
    if initial_check_usd_m <= 0:
        return float("nan")
    if exit_usd_m <= 0:
        return -1.0
    return (exit_usd_m / initial_check_usd_m) ** (1 / 5) - 1


# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------

def fmt_money(v: float, *, dollars: bool = True, decimals: int = 1) -> str:
    if v is None or (isinstance(v, float) and v != v):
        return "n/a"
    sign = "-" if v < 0 else ""
    av = abs(v)
    s = f"{sign}{'$' if dollars else ''}{av:,.{decimals}f}"
    return s


def fmt_pct(v: float, decimals: int = 1) -> str:
    if v is None or (isinstance(v, float) and v != v):
        return "n/a"
    return f"{v * 100:.{decimals}f}%"


def fmt_signed_pct(v: float, decimals: int = 1) -> str:
    if v is None or (isinstance(v, float) and v != v):
        return "n/a"
    return f"{v * 100:+.{decimals}f}%"
