/**
 * Real-data regression test: genuine LAMMPS EAM-copper phase-change
 * trajectories (generated by tools/sims/make_phase_trajectories.py and
 * committed gzipped) pushed through the exact multi-frame pipeline the
 * viewer uses — streaming parse → incremental .glimbin transcode →
 * LocalGlimbinSource read-back.
 *
 * Synthetic fixtures can't catch dialect drift in what LAMMPS actually
 * writes (scientific-notation box bounds, `pp pp ff` boundaries, column
 * ordering); these can.
 */

/// <reference types="node" />
import { describe, it, expect } from 'vitest';
import { gunzipSync } from 'node:zlib';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { GlimbinStreamWriter } from '@atlas/core/glimbin';
import type { Frame } from '@atlas/core/types';
import { canStreamDump, parseDumpStream } from './dumpStreamParser';
import { LocalGlimbinSource } from './LocalGlimbinSource';

const FIXTURES = dirname(fileURLToPath(import.meta.url));

function loadFixture(name: string): string {
  const gz = readFileSync(join(FIXTURES, '__fixtures__', name));
  return gunzipSync(gz).toString('utf8');
}

/** Worker-equivalent pass: parse all frames, transcode one at a time. */
async function transcode(text: string) {
  const writer = new GlimbinStreamWriter();
  const records: ArrayBuffer[] = [];
  let frame0: Frame | null = null;
  let firstPositions: Float32Array | null = null;
  let lastPositions: Float32Array | null = null;
  let natoms = 0;

  for await (const ev of parseDumpStream(text, { multiFrame: true })) {
    if (ev.type === 'header') {
      frame0 = ev.frame;
      natoms = ev.frame.natoms;
    } else if (ev.type === 'frame') {
      if (frame0) {
        firstPositions = frame0.positions.slice();
        records.push(writer.addFrame(frame0));
        frame0 = null;
      }
      lastPositions = ev.frame.positions.slice();
      records.push(writer.addFrame(ev.frame));
    }
  }
  const fin = writer.finalize();
  const blob = new Blob([fin.header, ...records, fin.index]);
  return { blob, meta: fin.meta, natoms, firstPositions, lastPositions };
}

describe.each([
  // Thresholds mirror each scenario's manifest `expected.min_moved_fraction`
  // (fraction of atoms past one Cu lattice constant ⇒ transformation real).
  { fixture: 'cu-melt-ci.lammpstrj.gz', label: 'Cu(100) slab melting', minMovedFraction: 0.3 },
  { fixture: 'cu-solidify-ci.lammpstrj.gz', label: 'liquid Cu rapid quench', minMovedFraction: 0.2 },
  { fixture: 'cu-sinter-ci.lammpstrj.gz', label: 'Cu nanoparticle sintering', minMovedFraction: 0.04 },
])('real LAMMPS trajectory: $label', ({ fixture, minMovedFraction }) => {
  it('passes the streaming gate, transcodes, and reads back', async () => {
    const text = loadFixture(fixture);

    // The viewer's pre-flight gate must accept what LAMMPS actually writes.
    expect(canStreamDump(text.slice(0, 4096))).toBe(true);

    const { blob, meta, natoms, firstPositions, lastPositions } = await transcode(text);
    expect(meta.totalFrames).toBeGreaterThan(10);
    expect(natoms).toBeGreaterThan(500);

    const source = new LocalGlimbinSource(blob);
    const opened = await source.open();
    expect(opened.totalFrames).toBe(meta.totalFrames);
    expect(opened.atomsPerFrame).toBe(natoms);

    // Exact round-trip of the first and last frames.
    const f0 = await source.fetchFrame(0);
    const fN = await source.fetchFrame(meta.totalFrames - 1);
    expect(Array.from(f0.positions)).toEqual(Array.from(firstPositions!));
    expect(Array.from(fN.positions)).toEqual(Array.from(lastPositions!));
    source.dispose();
  });

  it('captures a real transformation across the trajectory', async () => {
    const text = loadFixture(fixture);
    const { natoms, firstPositions, lastPositions } = await transcode(text);

    const CUTOFF_SQ = 3.6 * 3.6; // one Cu lattice constant, squared
    let moved = 0;
    for (let i = 0; i < natoms; i++) {
      const dx = lastPositions![i * 3] - firstPositions![i * 3];
      const dy = lastPositions![i * 3 + 1] - firstPositions![i * 3 + 1];
      const dz = lastPositions![i * 3 + 2] - firstPositions![i * 3 + 2];
      if (dx * dx + dy * dy + dz * dz > CUTOFF_SQ) moved++;
    }
    expect(moved / natoms).toBeGreaterThan(minMovedFraction);
  });
});
