import { useState, useCallback, useEffect, useRef, memo } from 'react';
import type { MoleculeData, Atom } from '@/components/MoleculeViewer';
import MoleculeViewer from '@/components/MoleculeViewer';
import AiInputPanel from '@/components/AiInputPanel';
import { motion, AnimatePresence } from 'framer-motion';
import { Toaster, toast } from 'sonner';
import {
  RotateCcw,
  Camera,
  Maximize2,
  Settings,
  Download,
  Copy,
  Check,
  Clock,
  FileText,
  Database,
  Box,
  AlertTriangle,
  X,
  Trash2,
  Hexagon,
  FlaskConical,
  Share2,
  Link,
} from 'lucide-react';
import {
  POPULAR_MOLECULES,
  parseXYZ,
  parseSDF,
  atomsToXYZ,
  calculateFormula,
  calculateMolecularWeight,
  getAtomCounts,
  fetchMoleculeFromPubChemByName,
  fetchMoleculeFromPubChemBySMILES,
} from '@/lib/molecules';
import type { HistoryEntry, MoleculeTemplate } from '@/lib/molecules';


// ============================
// Types
// ============================
type GenerationStep = 'idle' | 'parse' | 'fetch' | 'render' | 'done' | 'error';

interface ViewerSettings {
  autoRotate: boolean;
  showBonds: boolean;
  atomScale: number;
}

// ============================
// Utility Functions
// ============================
function generateId(): string {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
}

function formatTimestamp(ts: number): string {
  const diff = Date.now() - ts;
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return 'just now';
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.floor(hours / 24)}d ago`;
}

function copyToClipboard(text: string): Promise<void> {
  return navigator.clipboard.writeText(text);
}

function downloadText(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function moleculeToXYZ(molecule: MoleculeData, title?: string): string {
  return atomsToXYZ(molecule.atoms, title || 'Generated by LUPI');
}

function findTemplateByName(name: string): MoleculeTemplate | undefined {
  const lower = name.toLowerCase().trim();
  return POPULAR_MOLECULES.find(
    (m) =>
      m.name.toLowerCase() === lower ||
      m.name.toLowerCase().includes(lower) ||
      lower.includes(m.name.toLowerCase())
  );
}

// ============================
// Local Storage for History
// ============================
const HISTORY_KEY = 'lupi-studio-history';

function loadHistory(): HistoryEntry[] {
  try {
    const raw = localStorage.getItem(HISTORY_KEY);
    if (raw) {
      const parsed = JSON.parse(raw) as HistoryEntry[];
      return parsed.slice(0, 20);
    }
  } catch {
    // ignore
  }
  return [];
}

function saveHistory(history: HistoryEntry[]): void {
  try {
    localStorage.setItem(HISTORY_KEY, JSON.stringify(history.slice(0, 20)));
  } catch {
    // ignore
  }
}

// ============================
// CPK Color mapping for UI
// ============================
const CPK_COLORS: Record<string, string> = {
  H: '#FFFFFF',
  C: '#909090',
  N: '#3050F8',
  O: '#FF0D0D',
  F: '#90E050',
  P: '#FF8000',
  S: '#FFFF30',
  Cl: '#1FF01F',
  Fe: '#E06633',
  Cu: '#C78033',
  Zn: '#7D80B0',
};

function getAtomColor(element: string): string {
  return CPK_COLORS[element] || '#CCCCCC';
}

// ============================
// Property Panel Component
// ============================
function PropertyPanel({
  atoms,
  moleculeName,
  source,
  timestamp,
}: {
  atoms: Atom[];
  moleculeName: string;
  source: string;
  timestamp: number;
}) {
  const formula = calculateFormula(atoms);
  const weight = calculateMolecularWeight(atoms);
  const atomCounts = getAtomCounts(atoms);
  const maxCount = Math.max(...Object.values(atomCounts));

  return (
    <div className="space-y-4">
      <h3 className="font-body text-[14px] font-medium text-white tracking-wide">
        Properties
      </h3>

      {/* Molecular Formula */}
      <div>
        <p className="text-[11px] text-[rgba(255,255,255,0.4)] uppercase tracking-wider mb-1.5">
          Formula
        </p>
        <div className="font-mono text-[18px] flex flex-wrap gap-0.5">
          {formula.split(/([A-Z][a-z]?)(\d*)/).filter(Boolean).map((part, i) => {
            const isElement = /^[A-Z][a-z]?$/.test(part);
            if (isElement) {
              return (
                <span
                  key={i}
                  style={{ color: getAtomColor(part) }}
                  className="font-medium"
                >
                  {part}
                </span>
              );
            }
            return (
              <sub key={i} className="text-[13px] text-[rgba(255,255,255,0.7)]">
                {part}
              </sub>
            );
          })}
        </div>
      </div>

      {/* Atom Breakdown */}
      <div>
        <p className="text-[11px] text-[rgba(255,255,255,0.4)] uppercase tracking-wider mb-2">
          Atom Breakdown
        </p>
        <div className="space-y-1.5">
          {Object.entries(atomCounts)
            .sort((a, b) => b[1] - a[1])
            .map(([element, count]) => (
              <div key={element} className="flex items-center gap-2">
                <span
                  className="w-2.5 h-2.5 rounded-full shrink-0"
                  style={{ backgroundColor: getAtomColor(element) }}
                />
                <span className="text-[12px] text-[rgba(255,255,255,0.6)] w-6">
                  {element}
                </span>
                <div className="flex-1 h-1.5 bg-[rgba(255,255,255,0.08)] rounded-full overflow-hidden">
                  <motion.div
                    initial={{ width: 0 }}
                    animate={{ width: `${(count / maxCount) * 100}%` }}
                    transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] as [number, number, number, number] }}
                    className="h-full rounded-full"
                    style={{ backgroundColor: getAtomColor(element) }}
                  />
                </div>
                <span className="text-[12px] text-white font-mono w-5 text-right">
                  {count}
                </span>
              </div>
            ))}
        </div>
      </div>

      {/* Molecular Weight */}
      <div className="flex justify-between items-center">
        <span className="text-[11px] text-[rgba(255,255,255,0.4)] uppercase tracking-wider">
          Weight
        </span>
        <span className="text-[14px] text-white font-mono">
          {weight.toFixed(2)} <span className="text-[12px] text-[rgba(255,255,255,0.4)]">g/mol</span>
        </span>
      </div>

      {/* Atom Count */}
      <div className="flex justify-between items-center">
        <span className="text-[11px] text-[rgba(255,255,255,0.4)] uppercase tracking-wider">
          Atoms
        </span>
        <span className="text-[14px] text-white font-mono">
          {atoms.length} <span className="text-[12px] text-[rgba(255,255,255,0.4)]">total</span>
        </span>
      </div>

      {/* Source */}
      <div className="flex justify-between items-center">
        <span className="text-[11px] text-[rgba(255,255,255,0.4)] uppercase tracking-wider">
          Source
        </span>
        <span
          className={`text-[12px] font-mono ${
            source === 'PubChem'
              ? 'text-[#00E5FF]'
              : source === 'AI'
              ? 'text-lupi-violet'
              : 'text-[rgba(255,255,255,0.6)]'
          }`}
        >
          {source}
        </span>
      </div>

      {/* Molecule Name */}
      <div className="flex justify-between items-center">
        <span className="text-[11px] text-[rgba(255,255,255,0.4)] uppercase tracking-wider">
          Name
        </span>
        <span className="text-[12px] text-white">{moleculeName}</span>
      </div>

      {/* Timestamp */}
      <div className="flex justify-between items-center">
        <span className="text-[11px] text-[rgba(255,255,255,0.4)] uppercase tracking-wider">
          Generated
        </span>
        <span className="text-[12px] text-[rgba(255,255,255,0.3)]">
          {formatTimestamp(timestamp)}
        </span>
      </div>
    </div>
  );
}

// ============================
// Viewer Toolbar Component
// ============================
function ViewerToolbar({
  onReset,
  onScreenshot,
  onFullscreen,
  onDownload,
  settings,
  onSettingsChange,
}: {
  onReset: () => void;
  onScreenshot: () => void;
  onFullscreen: () => void;
  onDownload: () => void;
  settings: ViewerSettings;
  onSettingsChange: (s: ViewerSettings) => void;
}) {
  const [showSettings, setShowSettings] = useState(false);
  const [showExport, setShowExport] = useState(false);
  const settingsRef = useRef<HTMLDivElement>(null);
  const exportRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function handleClickOutside(e: MouseEvent) {
      if (settingsRef.current && !settingsRef.current.contains(e.target as Node)) {
        setShowSettings(false);
      }
      if (exportRef.current && !exportRef.current.contains(e.target as Node)) {
        setShowExport(false);
      }
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const buttons = [
    { icon: RotateCcw, label: 'Reset View', onClick: onReset },
    { icon: Camera, label: 'Screenshot', onClick: onScreenshot },
    { icon: Maximize2, label: 'Fullscreen', onClick: onFullscreen },
    { icon: Settings, label: 'Settings', onClick: () => setShowSettings(!showSettings) },
    { icon: Download, label: 'Export', onClick: () => setShowExport(!showExport) },
  ];

  return (
    <div className="relative">
      <div className="flex items-center gap-1 px-4 py-2 bg-[rgba(10,10,18,0.9)] backdrop-blur-md rounded-full border border-[rgba(255,255,255,0.08)]">
        {buttons.map((btn) => {
          const Icon = btn.icon;
          return (
            <button
              key={btn.label}
              onClick={btn.onClick}
              title={btn.label}
              className="w-9 h-9 flex items-center justify-center rounded-lg text-[rgba(255,255,255,0.5)] hover:text-white hover:bg-[rgba(255,255,255,0.08)] transition-all duration-200"
            >
              <Icon className="w-4 h-4" />
            </button>
          );
        })}
      </div>

      {/* Settings Popover */}
      <AnimatePresence>
        {showSettings && (
          <motion.div
            ref={settingsRef}
            initial={{ opacity: 0, y: 10, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 10, scale: 0.95 }}
            transition={{ duration: 0.2 }}
            className="absolute bottom-full left-1/2 -translate-x-1/2 mb-3 w-56 bg-[#10101C] border border-[rgba(255,255,255,0.1)] rounded-xl p-4 shadow-xl"
          >
            <h4 className="text-[12px] font-medium text-white mb-3">Viewer Settings</h4>
            <div className="space-y-3">
              {/* Auto-rotate toggle */}
              <div className="flex items-center justify-between">
                <span className="text-[12px] text-[rgba(255,255,255,0.6)]">Auto Rotate</span>
                <button
                  onClick={() =>
                    onSettingsChange({ ...settings, autoRotate: !settings.autoRotate })
                  }
                  className={`w-9 h-5 rounded-full transition-colors duration-200 ${
                    settings.autoRotate ? 'bg-lupi-violet' : 'bg-[rgba(255,255,255,0.15)]'
                  }`}
                >
                  <div
                    className={`w-3.5 h-3.5 bg-white rounded-full transition-transform duration-200 ${
                      settings.autoRotate ? 'translate-x-4' : 'translate-x-0.5'
                    }`}
                  />
                </button>
              </div>

              {/* Show bonds toggle */}
              <div className="flex items-center justify-between">
                <span className="text-[12px] text-[rgba(255,255,255,0.6)]">Show Bonds</span>
                <button
                  onClick={() =>
                    onSettingsChange({ ...settings, showBonds: !settings.showBonds })
                  }
                  className={`w-9 h-5 rounded-full transition-colors duration-200 ${
                    settings.showBonds ? 'bg-lupi-violet' : 'bg-[rgba(255,255,255,0.15)]'
                  }`}
                >
                  <div
                    className={`w-3.5 h-3.5 bg-white rounded-full transition-transform duration-200 ${
                      settings.showBonds ? 'translate-x-4' : 'translate-x-0.5'
                    }`}
                  />
                </button>
              </div>

              {/* Atom Scale */}
              <div>
                <span className="text-[12px] text-[rgba(255,255,255,0.6)]">Atom Scale</span>
                <input
                  type="range"
                  min="0.5"
                  max="2"
                  step="0.1"
                  value={settings.atomScale}
                  onChange={(e) =>
                    onSettingsChange({ ...settings, atomScale: parseFloat(e.target.value) })
                  }
                  className="w-full mt-1.5 accent-lupi-violet"
                />
                <span className="text-[11px] text-[rgba(255,255,255,0.4)] font-mono">
                  {settings.atomScale.toFixed(1)}x
                </span>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Export Dropdown */}
      <AnimatePresence>
        {showExport && (
          <motion.div
            ref={exportRef}
            initial={{ opacity: 0, y: 10, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 10, scale: 0.95 }}
            transition={{ duration: 0.2 }}
            className="absolute bottom-full left-1/2 -translate-x-1/2 mb-3 w-52 bg-[#10101C] border border-[rgba(255,255,255,0.1)] rounded-xl py-2 shadow-xl"
          >
            <button
              onClick={() => {
                onDownload();
                setShowExport(false);
              }}
              className="w-full flex items-center gap-2.5 px-3 py-2 text-[13px] text-[rgba(255,255,255,0.7)] hover:text-white hover:bg-[rgba(255,255,255,0.05)] transition-colors"
            >
              <FileText className="w-4 h-4" />
              Download XYZ
            </button>
            <button
              onClick={() => {
                onDownload();
                setShowExport(false);
              }}
              className="w-full flex items-center gap-2.5 px-3 py-2 text-[13px] text-[rgba(255,255,255,0.7)] hover:text-white hover:bg-[rgba(255,255,255,0.05)] transition-colors"
            >
              <Database className="w-4 h-4" />
              Download SDF
            </button>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

// ============================
// Pipeline Visualizer Component
// ============================
const PipelineVisualizer = memo(function PipelineVisualizer({
  step,
}: {
  step: GenerationStep;
}) {
  const steps: { id: GenerationStep; label: string; icon: typeof FileText; desc: string }[] = [
    { id: 'parse', label: 'Parse', icon: FileText, desc: 'Parse input → identify compound' },
    { id: 'fetch', label: 'Fetch', icon: Database, desc: 'Query 3D coordinates' },
    { id: 'render', label: 'Render', icon: Box, desc: 'Build 3D scene' },
  ];

  const stepIndex =
    step === 'parse' ? 0 : step === 'fetch' ? 1 : step === 'render' ? 2 : step === 'done' ? 3 : -1;

  return (
    <div className="w-full py-16 px-6">
      <div className="max-w-3xl mx-auto">
        <div className="flex items-center justify-between relative">
          {/* Connecting lines */}
          <div className="absolute top-6 left-0 right-0 h-px bg-[rgba(255,255,255,0.08)]" />
          <motion.div
            className="absolute top-6 left-0 h-px bg-gradient-to-r from-lupi-violet to-[#00E5FF]"
            initial={{ width: '0%' }}
            animate={{
              width: step === 'done' ? '100%' : step === 'idle' || step === 'error' ? '0%' : `${(stepIndex / 2) * 100}%`,
            }}
            transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] as [number, number, number, number] }}
          />

          {steps.map((s, i) => {
            const Icon = s.icon;
            const isActive = i <= stepIndex && step !== 'idle' && step !== 'error';
            const isCurrent = i === stepIndex && step !== 'done';

            return (
              <div key={s.id} className="relative flex flex-col items-center z-10">
                <motion.div
                  animate={{
                    scale: isCurrent ? 1.1 : 1,
                    borderColor: isActive ? '#7B5CFF' : 'rgba(255,255,255,0.15)',
                    backgroundColor: isActive ? 'rgba(123,92,255,0.15)' : '#0A0A12',
                  }}
                  className="w-12 h-12 rounded-full border-2 flex items-center justify-center"
                >
                  <Icon
                    className={`w-5 h-5 ${
                      isActive ? 'text-lupi-violet' : 'text-[rgba(255,255,255,0.3)]'
                    }`}
                  />
                </motion.div>

                {/* Pulse dot for current step */}
                {isCurrent && (
                  <motion.div
                    className="absolute top-0 right-0 w-3 h-3 bg-[#00E5FF] rounded-full"
                    animate={{ scale: [1, 1.3, 1], opacity: [1, 0.6, 1] }}
                    transition={{ duration: 1.5, repeat: Infinity }}
                  />
                )}

                <p
                  className={`mt-2 text-[13px] font-medium ${
                    isActive ? 'text-white' : 'text-[rgba(255,255,255,0.4)]'
                  }`}
                >
                  {s.label}
                </p>
                <p className="mt-0.5 text-[11px] text-[rgba(255,255,255,0.3)] max-w-[120px] text-center">
                  {s.desc}
                </p>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
});

// ============================
// Template Grid Component
// ============================
const TemplateGrid = memo(function TemplateGrid({
  onSelect,
}: {
  onSelect: (template: MoleculeTemplate) => void;
}) {
  const quickPicks = POPULAR_MOLECULES.slice(0, 8); // First 8

  return (
    <div className="w-full py-20 px-6 bg-[#0A0A12]">
      <div className="max-w-content mx-auto">
        <h3 className="font-body text-[18px] font-medium text-white mb-8">
          Quick Start Templates
        </h3>
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
          {quickPicks.map((template, i) => {
            const atoms = template.data.atoms;
            const formula = calculateFormula(atoms);
            const firstElement = atoms[0]?.element || 'C';
            return (
              <motion.button
                key={template.name}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{
                  duration: 0.4,
                  delay: i * 0.05,
                  ease: [0.16, 1, 0.3, 1] as [number, number, number, number],
                }}
                onClick={() => onSelect(template)}
                className="flex flex-col items-start gap-2 p-4 bg-[#10101C] border border-[rgba(255,255,255,0.08)] rounded-xl hover:border-lupi-violet/40 hover:bg-[rgba(123,92,255,0.05)] hover:scale-[1.02] transition-all duration-300 text-left group"
              >
                <div className="flex items-center gap-2">
                  <span
                    className="w-3 h-3 rounded-full shrink-0"
                    style={{ backgroundColor: getAtomColor(firstElement) }}
                  />
                  <span className="font-body text-[14px] font-medium text-white group-hover:text-lupi-violet-light transition-colors">
                    {template.name}
                  </span>
                </div>
                <span className="font-mono text-[11px] text-[rgba(255,255,255,0.4)]">
                  {formula}
                </span>
                {template.description && (
                  <span className="text-[11px] text-[rgba(255,255,255,0.3)] leading-relaxed line-clamp-1">
                    {template.description}
                  </span>
                )}
                <div className="flex gap-1.5 mt-1 flex-wrap">
                  {template.tags?.map((tag) => (
                    <span
                      key={tag}
                      className="px-1.5 py-0.5 bg-[rgba(255,255,255,0.06)] rounded text-[10px] text-[rgba(255,255,255,0.4)]"
                    >
                      {tag}
                    </span>
                  ))}
                </div>
              </motion.button>
            );
          })}
        </div>
      </div>
    </div>
  );
});

// ============================
// Export Panel Component
// ============================
function ExportPanel({
  molecule,
  moleculeName,
}: {
  molecule: MoleculeData | null;
  moleculeName: string;
}) {
  const [copiedLink, setCopiedLink] = useState(false);
  const [copiedEmbed, setCopiedEmbed] = useState(false);

  if (!molecule) return null;

  const xyz = moleculeToXYZ(molecule, moleculeName);
  const formula = calculateFormula(molecule.atoms);

  const handleCopyLink = () => {
    const link = `https://lupi.design/m/${formula}-${generateId().slice(0, 6)}`;
    copyToClipboard(link).then(() => {
      setCopiedLink(true);
      setTimeout(() => setCopiedLink(false), 2000);
      toast.success('Link copied to clipboard');
    });
  };

  const handleCopyEmbed = () => {
    const embed = `<iframe src="https://lupi.design/embed/${formula}" width="600" height="400" frameborder="0"></iframe>`;
    copyToClipboard(embed).then(() => {
      setCopiedEmbed(true);
      setTimeout(() => setCopiedEmbed(false), 2000);
      toast.success('Embed code copied');
    });
  };

  return (
    <div className="w-full py-20 px-6">
      <div className="max-w-content mx-auto">
        <motion.h3
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="font-display text-h3 text-white mb-10"
        >
          Export Your Molecule
        </motion.h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {/* Export Formats */}
          <div className="space-y-4">
            <h4 className="text-[14px] font-medium text-white mb-4">Export Formats</h4>
            {[
              {
                label: 'XYZ',
                desc: 'Standard coordinate format — compatible with LAMMPS, VMD, Avogadro',
                ext: 'xyz',
              },
              {
                label: 'SDF',
                desc: 'Structure Data Format — includes bonding information',
                ext: 'sdf',
              },
              {
                label: 'PNG',
                desc: 'High-resolution render with transparent background',
                ext: 'png',
              },
              {
                label: 'JSON',
                desc: 'Raw atom data with coordinates, elements, and bonds',
                ext: 'json',
              },
            ].map((fmt) => (
              <motion.div
                key={fmt.label}
                initial={{ opacity: 0, x: -20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4 }}
                className="flex items-center justify-between p-4 bg-[#0A0A12] border border-[rgba(255,255,255,0.08)] rounded-xl"
              >
                <div>
                  <span className="text-[14px] font-medium text-white">{fmt.label}</span>
                  <p className="text-[12px] text-[rgba(255,255,255,0.4)] mt-0.5">{fmt.desc}</p>
                </div>
                <button
                  onClick={() => {
                    if (fmt.label === 'XYZ') {
                      downloadText(`${moleculeName.replace(/\s+/g, '_')}.xyz`, xyz);
                    } else if (fmt.label === 'JSON') {
                      downloadText(
                        `${moleculeName.replace(/\s+/g, '_')}.json`,
                        JSON.stringify(molecule, null, 2)
                      );
                    } else {
                      toast.info(`${fmt.label} export coming soon`);
                    }
                  }}
                  className="flex items-center gap-1.5 px-3 py-1.5 bg-[rgba(123,92,255,0.15)] text-lupi-violet text-[12px] font-medium rounded-lg hover:bg-[rgba(123,92,255,0.25)] transition-colors"
                >
                  <Download className="w-3.5 h-3.5" />
                  Download
                </button>
              </motion.div>
            ))}
          </div>

          {/* Share Options */}
          <div className="space-y-6">
            <h4 className="text-[14px] font-medium text-white mb-4">Share</h4>

            {/* Permalink */}
            <div className="p-4 bg-[#0A0A12] border border-[rgba(255,255,255,0.08)] rounded-xl">
              <label className="text-[12px] text-[rgba(255,255,255,0.4)] mb-2 block">
                Permalink
              </label>
              <div className="flex items-center gap-2">
                <div className="flex-1 px-3 py-2 bg-[#10101C] rounded-lg border border-[rgba(255,255,255,0.08)] font-mono text-[12px] text-[rgba(255,255,255,0.5)] truncate">
                  lupi.design/m/{formula}-{generateId().slice(0, 6)}
                </div>
                <button
                  onClick={handleCopyLink}
                  className="p-2 rounded-lg bg-[rgba(123,92,255,0.15)] text-lupi-violet hover:bg-[rgba(123,92,255,0.25)] transition-colors"
                >
                  {copiedLink ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                </button>
              </div>
            </div>

            {/* Embed Code */}
            <div className="p-4 bg-[#0A0A12] border border-[rgba(255,255,255,0.08)] rounded-xl">
              <label className="text-[12px] text-[rgba(255,255,255,0.4)] mb-2 block">
                Embed Code
              </label>
              <div className="flex items-center gap-2">
                <div className="flex-1 px-3 py-2 bg-[#10101C] rounded-lg border border-[rgba(255,255,255,0.08)] font-mono text-[11px] text-[rgba(255,255,255,0.5)] truncate">
                  {`<iframe src="https://lupi.design/embed/${formula}"...>`}
                </div>
                <button
                  onClick={handleCopyEmbed}
                  className="p-2 rounded-lg bg-[rgba(123,92,255,0.15)] text-lupi-violet hover:bg-[rgba(123,92,255,0.25)] transition-colors"
                >
                  {copiedEmbed ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                </button>
              </div>
            </div>

            {/* Social Share */}
            <div className="flex gap-3">
              <button
                onClick={() => toast.info('Twitter sharing coming soon')}
                className="flex items-center gap-2 px-4 py-2 bg-[#0A0A12] border border-[rgba(255,255,255,0.08)] rounded-lg text-[13px] text-[rgba(255,255,255,0.6)] hover:text-white hover:border-[rgba(255,255,255,0.15)] transition-colors"
              >
                <Share2 className="w-4 h-4" />
                Twitter
              </button>
              <button
                onClick={() => toast.info('LinkedIn sharing coming soon')}
                className="flex items-center gap-2 px-4 py-2 bg-[#0A0A12] border border-[rgba(255,255,255,0.08)] rounded-lg text-[13px] text-[rgba(255,255,255,0.6)] hover:text-white hover:border-[rgba(255,255,255,0.15)] transition-colors"
              >
                <Link className="w-4 h-4" />
                LinkedIn
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// ============================
// Main Studio Component
// ============================
export default function Studio() {
  const [moleculeData, setMoleculeData] = useState<MoleculeData | null>(null);
  const [moleculeName, setMoleculeName] = useState<string>('Caffeine');
  const [source, setSource] = useState<'PubChem' | 'AI' | 'Manual'>('Manual');
  const [loading, setLoading] = useState(false);
  const [loadingMessage, setLoadingMessage] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [history, setHistory] = useState<HistoryEntry[]>([]);
  const [generationStep, setGenerationStep] = useState<GenerationStep>('idle');
  const [viewerSettings, setViewerSettings] = useState<ViewerSettings>({
    autoRotate: true,
    showBonds: true,
    atomScale: 1.0,
  });
  const [copySmiles, setCopySmiles] = useState(false);
  const viewerContainerRef = useRef<HTMLDivElement>(null);

  // Load history from localStorage on mount
  useEffect(() => {
    setHistory(loadHistory());
  }, []);

  // Load default molecule (Caffeine) on mount
  useEffect(() => {
    const caffeine = POPULAR_MOLECULES.find((m) => m.name === 'Caffeine');
    if (caffeine) {
      setMoleculeData(caffeine.data);
      setMoleculeName(caffeine.name);
      setSource('Manual');
    }
  }, []);

  // Save history on change
  useEffect(() => {
    saveHistory(history);
  }, [history]);

  // ============================
  // Molecule Generation Logic
  // ============================
  const handleGenerate = useCallback(
    async ({ mode, value }: { mode: string; value: string }) => {
      if (!value.trim()) return;

      setLoading(true);
      setError(null);
      setGenerationStep('parse');

      try {
        let result: MoleculeData | null = null;
        let name = value.trim();
        let src: 'PubChem' | 'AI' | 'Manual' = 'Manual';

        if (mode === 'natural') {
          setLoadingMessage('Resolving molecule name...');
          setGenerationStep('parse');

          // Check popular templates first
          const template = findTemplateByName(value);
          if (template) {
            result = template.data;
            name = template.name;
            src = 'Manual';
            setGenerationStep('render');
          } else {
            setLoadingMessage('Fetching from PubChem...');
            setGenerationStep('fetch');
            try {
              const { moleculeData: md } = await fetchMoleculeFromPubChemByName(value);
              result = md;
              src = 'PubChem';
              name = value.trim();
            } catch (pubchemErr: unknown) {
              // Fallback: try to find similar template
              const fallbackTemplate = POPULAR_MOLECULES.find(
                (m) =>
                  value.toLowerCase().includes(m.name.toLowerCase()) ||
                  m.tags?.some((t) => value.toLowerCase().includes(t.toLowerCase()))
              );
              if (fallbackTemplate) {
                result = fallbackTemplate.data;
                name = fallbackTemplate.name;
                src = 'AI';
                setGenerationStep('render');
              } else {
                throw pubchemErr;
              }
            }
          }
        } else if (mode === 'smiles') {
          setLoadingMessage('Parsing SMILES...');
          setGenerationStep('parse');

          // Try PubChem first
          setLoadingMessage('Fetching 3D from PubChem...');
          setGenerationStep('fetch');
          try {
            const { moleculeData: md } = await fetchMoleculeFromPubChemBySMILES(value);
            result = md;
            src = 'PubChem';
            name = `SMILES: ${value.slice(0, 20)}${value.length > 20 ? '...' : ''}`;
          } catch {
            setError('Could not resolve SMILES via PubChem. Try a different notation or use a molecule name instead.');
            setGenerationStep('error');
            setLoading(false);
            return;
          }
        } else if (mode === 'xyz') {
          setLoadingMessage('Parsing XYZ coordinates...');
          setGenerationStep('parse');
          result = parseXYZ(value);
          name = 'Custom XYZ';
          src = 'Manual';
          setGenerationStep('render');
          if (!result) {
            setError('Invalid XYZ format. Expected: atom_count, title line, then element x y z per line.');
            setGenerationStep('error');
            setLoading(false);
            return;
          }
        } else if (mode === 'upload') {
          setLoadingMessage('Parsing file...');
          setGenerationStep('parse');
          const trimmed = value.trim();
          if (trimmed.includes('$$$$') || trimmed.includes('M  END')) {
            result = parseSDF(trimmed);
            name = 'Uploaded SDF';
          } else {
            result = parseXYZ(trimmed);
            name = 'Uploaded XYZ';
          }
          src = 'Manual';
          setGenerationStep('render');
          if (!result) {
            setError('Could not parse file. Supported formats: XYZ, SDF, PDB, MOL.');
            setGenerationStep('error');
            setLoading(false);
            return;
          }
        }

        if (result) {
          setGenerationStep('render');
          await new Promise((r) => setTimeout(r, 300)); // Brief pause for render effect
          setMoleculeData(result);
          setMoleculeName(name);
          setSource(src);
          setGenerationStep('done');

          // Add to history
          const entry: HistoryEntry = {
            id: generateId(),
            name,
            formula: calculateFormula(result.atoms),
            atoms: result.atoms,
            source: src,
            timestamp: Date.now(),
          };
          setHistory((prev) => [entry, ...prev].slice(0, 20));

          toast.success(`${name} loaded successfully`);
        }
      } catch (err: unknown) {
        const message = err instanceof Error ? err.message : 'An unknown error occurred';
        setError(message);
        setGenerationStep('error');
        toast.error(message);
      } finally {
        setLoading(false);
        setLoadingMessage('');
      }
    },
    []
  );

  // ============================
  // Quick Prompts
  // ============================
  const quickPrompts = ['Caffeine', 'Aspirin', 'Dopamine', 'Benzene', 'Buckminsterfullerene'];

  const handleQuickPrompt = useCallback((name: string) => {
    const template = POPULAR_MOLECULES.find((m) => m.name === name);
    if (template) {
      setMoleculeData(template.data);
      setMoleculeName(template.name);
      setSource('Manual');
      setError(null);

      const entry: HistoryEntry = {
        id: generateId(),
        name: template.name,
        formula: calculateFormula(template.data.atoms),
        atoms: template.data.atoms,
        source: 'Manual',
        timestamp: Date.now(),
      };
      setHistory((prev) => [entry, ...prev].slice(0, 20));
      toast.success(`${template.name} loaded`);
    }
  }, []);

  // ============================
  // History Actions
  // ============================
  const handleLoadHistoryEntry = useCallback((entry: HistoryEntry) => {
    setMoleculeData({ atoms: entry.atoms });
    setMoleculeName(entry.name);
    setSource(entry.source);
    setError(null);
  }, []);

  const handleClearHistory = useCallback(() => {
    setHistory([]);
    toast.success('History cleared');
  }, []);

  // ============================
  // Viewer Toolbar Actions
  // ============================
  const handleReset = useCallback(() => {
    // Reset is handled by MoleculeViewer internally via key prop
    setMoleculeData((prev) => (prev ? { ...prev, atoms: [...prev.atoms] } : null));
  }, []);

  const handleScreenshot = useCallback(() => {
    toast.info('Screenshot feature coming soon');
  }, []);

  const handleFullscreen = useCallback(() => {
    if (viewerContainerRef.current) {
      if (document.fullscreenElement) {
        document.exitFullscreen();
      } else {
        viewerContainerRef.current.requestFullscreen();
      }
    }
  }, []);

  const handleDownload = useCallback(() => {
    if (moleculeData) {
      downloadText(
        `${moleculeName.replace(/\s+/g, '_')}.xyz`,
        moleculeToXYZ(moleculeData, moleculeName)
      );
      toast.success('XYZ file downloaded');
    }
  }, [moleculeData, moleculeName]);

  const handleCopySMILES = useCallback(() => {
    const template = POPULAR_MOLECULES.find((m) => m.name === moleculeName);
    if (template?.smiles) {
      copyToClipboard(template.smiles).then(() => {
        setCopySmiles(true);
        setTimeout(() => setCopySmiles(false), 2000);
        toast.success('SMILES copied to clipboard');
      });
    } else {
      toast.info('SMILES not available for this molecule');
    }
  }, [moleculeName]);

  // ============================
  // Template Selection
  // ============================
  const handleTemplateSelect = useCallback((template: MoleculeTemplate) => {
    setMoleculeData(template.data);
    setMoleculeName(template.name);
    setSource('Manual');
    setError(null);

    const entry: HistoryEntry = {
      id: generateId(),
      name: template.name,
      formula: calculateFormula(template.data.atoms),
      atoms: template.data.atoms,
      source: 'Manual',
      timestamp: Date.now(),
    };
    setHistory((prev) => [entry, ...prev].slice(0, 20));
    toast.success(`${template.name} loaded`);

    // Scroll to top to show the molecule
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }, []);

  // Current molecule info
  const currentFormula = moleculeData ? calculateFormula(moleculeData.atoms) : '';

  return (
    <div className="min-h-[100dvh] bg-void-black">
      <Toaster
        position="top-right"
        toastOptions={{
          style: {
            background: '#10101C',
            border: '1px solid rgba(255,255,255,0.08)',
            color: '#fff',
          },
        }}
      />

      {/* ============================ */}
      {/* Section 1: Studio Workspace  */}
      {/* ============================ */}
      <div
        className="flex flex-col lg:flex-row"
        style={{ height: 'calc(100dvh - 64px)' }}
      >
        {/* Left Panel (~40%) */}
        <div className="w-full lg:w-[40%] flex flex-col border-r border-[rgba(255,255,255,0.06)] bg-[#0A0A12] overflow-hidden">
          {/* Scrollable content */}
          <div className="flex-1 overflow-y-auto custom-scrollbar">
            <div className="p-5 space-y-5">
              {/* Header */}
              <div>
                <h1 className="font-display text-[28px] font-light text-white tracking-tight mb-1">
                  Studio
                </h1>
                <p className="text-[13px] text-[rgba(255,255,255,0.4)]">
                  AI molecular design interface
                </p>
              </div>

              {/* AI Input Panel */}
              <AiInputPanel onSubmit={handleGenerate} loading={loading} />

              {/* Quick Prompts */}
              <div className="flex flex-wrap gap-2">
                {quickPrompts.map((name) => (
                  <button
                    key={name}
                    onClick={() => handleQuickPrompt(name)}
                    className="px-3 py-1.5 bg-[#10101C] border border-[rgba(255,255,255,0.08)] rounded-full text-[12px] text-[rgba(255,255,255,0.6)] hover:border-lupi-violet/40 hover:text-white transition-all duration-200"
                  >
                    {name}
                  </button>
                ))}
              </div>

              {/* Loading State */}
              <AnimatePresence>
                {loading && (
                  <motion.div
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: 'auto' }}
                    exit={{ opacity: 0, height: 0 }}
                    className="overflow-hidden"
                  >
                    <div className="p-3 bg-[rgba(123,92,255,0.08)] border border-[rgba(123,92,255,0.2)] rounded-lg flex items-center gap-3">
                      <div className="w-5 h-5 border-2 border-lupi-violet border-t-transparent rounded-full animate-spin shrink-0" />
                      <div className="flex-1 min-w-0">
                        <p className="text-[13px] text-lupi-violet-light truncate">
                          {loadingMessage || 'Processing...'}
                        </p>
                      </div>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>

              {/* Error State */}
              <AnimatePresence>
                {error && (
                  <motion.div
                    initial={{ opacity: 0, y: -10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -10 }}
                    className="p-3 bg-[rgba(255,46,99,0.08)] border border-[rgba(255,46,99,0.2)] rounded-lg flex items-start gap-3"
                  >
                    <AlertTriangle className="w-5 h-5 text-[#FF2E63] shrink-0 mt-0.5" />
                    <div className="flex-1 min-w-0">
                      <p className="text-[13px] text-[#FF2E63]">{error}</p>
                    </div>
                    <button
                      onClick={() => setError(null)}
                      className="shrink-0 text-[rgba(255,255,255,0.4)] hover:text-white"
                    >
                      <X className="w-4 h-4" />
                    </button>
                  </motion.div>
                )}
              </AnimatePresence>

              {/* Divider */}
              <div className="border-t border-[rgba(255,255,255,0.08)]" />

              {/* Generation History */}
              <div>
                <div className="flex items-center justify-between mb-3">
                  <h3 className="font-body text-[14px] font-medium text-white tracking-wide flex items-center gap-2">
                    <Clock className="w-4 h-4 text-[rgba(255,255,255,0.4)]" />
                    Recent
                  </h3>
                  {history.length > 0 && (
                    <button
                      onClick={handleClearHistory}
                      className="text-[11px] text-[rgba(255,255,255,0.3)] hover:text-[#FF2E63] transition-colors flex items-center gap-1"
                    >
                      <Trash2 className="w-3 h-3" />
                      Clear
                    </button>
                  )}
                </div>

                {history.length === 0 ? (
                  <p className="text-center text-[13px] text-[rgba(255,255,255,0.3)] py-6">
                    No molecules yet. Generate your first above.
                  </p>
                ) : (
                  <div className="space-y-1">
                    <AnimatePresence>
                      {history.map((entry) => (
                        <motion.button
                          key={entry.id}
                          initial={{ opacity: 0, x: -10 }}
                          animate={{ opacity: 1, x: 0 }}
                          exit={{ opacity: 0, x: 10 }}
                          onClick={() => handleLoadHistoryEntry(entry)}
                          className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-left transition-all duration-200 group ${
                            moleculeName === entry.name
                              ? 'bg-[rgba(123,92,255,0.12)] border border-[rgba(123,92,255,0.25)]'
                              : 'hover:bg-[#10101C] border border-transparent'
                          }`}
                        >
                          <span
                            className="w-2.5 h-2.5 rounded-full shrink-0"
                            style={{
                              backgroundColor: getAtomColor(entry.atoms[0]?.element || 'C'),
                            }}
                          />
                          <div className="flex-1 min-w-0">
                            <p className="text-[13px] text-white truncate">{entry.name}</p>
                            <p className="text-[11px] text-[rgba(255,255,255,0.4)] font-mono">
                              {entry.formula}
                            </p>
                          </div>
                          <span className="text-[11px] text-[rgba(255,255,255,0.25)] shrink-0">
                            {formatTimestamp(entry.timestamp)}
                          </span>
                        </motion.button>
                      ))}
                    </AnimatePresence>
                  </div>
                )}
              </div>

              {/* Divider */}
              <div className="border-t border-[rgba(255,255,255,0.08)]" />

              {/* Properties Panel */}
              {moleculeData && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ duration: 0.3 }}
                >
                  <PropertyPanel
                    atoms={moleculeData.atoms}
                    moleculeName={moleculeName}
                    source={source}
                    timestamp={Date.now()}
                  />
                </motion.div>
              )}

              {/* Export Controls (mini) */}
              {moleculeData && (
                <div className="flex gap-2">
                  <button
                    onClick={handleDownload}
                    className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-[#10101C] border border-[rgba(255,255,255,0.08)] rounded-lg text-[12px] text-[rgba(255,255,255,0.6)] hover:text-white hover:border-[rgba(255,255,255,0.15)] transition-colors"
                  >
                    <Download className="w-3.5 h-3.5" />
                    XYZ
                  </button>
                  <button
                    onClick={handleCopySMILES}
                    className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-[#10101C] border border-[rgba(255,255,255,0.08)] rounded-lg text-[12px] text-[rgba(255,255,255,0.6)] hover:text-white hover:border-[rgba(255,255,255,0.15)] transition-colors"
                  >
                    {copySmiles ? (
                      <Check className="w-3.5 h-3.5 text-[#00E5FF]" />
                    ) : (
                      <Copy className="w-3.5 h-3.5" />
                    )}
                    SMILES
                  </button>
                  <button
                    onClick={() => {
                      const link = `https://lupi.design/m/${currentFormula}-${generateId().slice(0, 6)}`;
                      copyToClipboard(link).then(() => toast.success('Link copied'));
                    }}
                    className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-[#10101C] border border-[rgba(255,255,255,0.08)] rounded-lg text-[12px] text-[rgba(255,255,255,0.6)] hover:text-white hover:border-[rgba(255,255,255,0.15)] transition-colors"
                  >
                    <Share2 className="w-3.5 h-3.5" />
                    Share
                  </button>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Right Panel (~60%) */}
        <div
          ref={viewerContainerRef}
          className="w-full lg:w-[60%] relative bg-void-black"
          style={{ minHeight: '400px' }}
        >
          {moleculeData ? (
            <MoleculeViewer
              key={`${moleculeName}-${moleculeData.atoms.length}`}
              moleculeData={moleculeData}
              width="100%"
              height="100%"
              autoRotate={viewerSettings.autoRotate}
              interactive={true}
              showBonds={viewerSettings.showBonds}
              atomScale={viewerSettings.atomScale}
            />
          ) : (
            <div className="w-full h-full flex items-center justify-center">
              <div className="text-center">
                <Hexagon className="w-12 h-12 text-[rgba(255,255,255,0.1)] mx-auto mb-3" />
                <p className="text-[14px] text-[rgba(255,255,255,0.4)]">
                  Enter a molecule name or select a template
                </p>
              </div>
            </div>
          )}

          {/* Floating Toolbar */}
          <div className="absolute bottom-6 left-1/2 -translate-x-1/2 z-10">
            <ViewerToolbar
              onReset={handleReset}
              onScreenshot={handleScreenshot}
              onFullscreen={handleFullscreen}
              onDownload={handleDownload}
              settings={viewerSettings}
              onSettingsChange={setViewerSettings}
            />
          </div>

          {/* Molecule name overlay */}
          {moleculeData && (
            <motion.div
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              className="absolute top-4 left-4 z-10 px-3 py-1.5 bg-[rgba(10,10,18,0.8)] backdrop-blur-md border border-[rgba(255,255,255,0.08)] rounded-lg"
            >
              <div className="flex items-center gap-2">
                <FlaskConical className="w-3.5 h-3.5 text-lupi-violet" />
                <span className="text-[13px] text-white font-medium">{moleculeName}</span>
                <span className="text-[11px] text-[rgba(255,255,255,0.4)] font-mono">
                  {currentFormula}
                </span>
              </div>
            </motion.div>
          )}

          {/* Source badge */}
          {moleculeData && (
            <div className="absolute top-4 right-4 z-10 px-2.5 py-1 bg-[rgba(10,10,18,0.8)] backdrop-blur-md border border-[rgba(255,255,255,0.08)] rounded-lg">
              <span
                className={`text-[11px] font-mono ${
                  source === 'PubChem'
                    ? 'text-[#00E5FF]'
                    : source === 'AI'
                    ? 'text-lupi-violet'
                    : 'text-[rgba(255,255,255,0.5)]'
                }`}
              >
                {source}
              </span>
            </div>
          )}
        </div>
      </div>

      {/* ============================ */}
      {/* Section 2: Pipeline Visual  */}
      {/* ============================ */}
      <PipelineVisualizer step={generationStep} />

      {/* ============================ */}
      {/* Section 3: Quick Templates  */}
      {/* ============================ */}
      <TemplateGrid onSelect={handleTemplateSelect} />

      {/* ============================ */}
      {/* Section 4: Export & Share   */}
      {/* ============================ */}
      <ExportPanel molecule={moleculeData} moleculeName={moleculeName} />
    </div>
  );
}
