"""
Pydantic schemas for interatomic potential validation.

These models define the structured types that flow through DSPy signatures,
mirroring the Rust `BenchmarkRecord` and `AgentClaim` types from atlas-distill.
"""

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ─────────────────────────────────────────────────────────────
# Benchmark Data Types
# ─────────────────────────────────────────────────────────────


class CrystalStructure(str, Enum):
    FCC = "fcc"
    BCC = "bcc"
    HCP = "hcp"
    DIAMOND = "diamond"


class BenchmarkRecord(BaseModel):
    """A single measured vs. predicted property for one potential."""

    element: str = Field(description="Element symbol, e.g. 'Al', 'Cu'")
    potential_id: str = Field(description="NIST IPR identifier")
    potential_label: str = Field(description="Short name, e.g. 'Mishin-1999'")
    pair_style: str = Field(description="LAMMPS pair_style, e.g. 'eam/alloy'")
    property: str = Field(description="Physical property, e.g. 'C11', 'C12', 'C44'")
    reference: float = Field(description="Experimental reference value (GPa)")
    predicted: float = Field(description="Potential-predicted value (GPa)")
    unit: str = Field(default="GPa")
    error_pct: Optional[float] = Field(
        default=None,
        description="Percentage error: 100 * (predicted - reference) / reference",
    )

    def compute_error(self) -> float:
        if self.reference != 0:
            self.error_pct = 100.0 * (self.predicted - self.reference) / self.reference
        else:
            self.error_pct = 0.0
        return self.error_pct


# ─────────────────────────────────────────────────────────────
# Manifold Analysis Types
# ─────────────────────────────────────────────────────────────


class ManifoldResult(BaseModel):
    """Output of PCA-based error manifold analysis."""

    potential: str
    n_materials: int
    n_properties: int
    participation_ratio: float = Field(
        description="Effective dimensionality: (Σλ)² / Σλ². < 2 → hyper-ribbon."
    )
    top_eigenvalue_fraction: float = Field(
        description="Fraction of variance captured by the first principal component"
    )
    is_hyper_ribbon: bool
    principal_direction: list[float] = Field(
        description="First eigenvector — the 'spine' of the error ribbon"
    )


class UniversalAlignmentResult(BaseModel):
    """Comparison of principal error axes between two potential families."""

    potential_a: str
    potential_b: str
    cosine_similarity: float = Field(
        description="Absolute cosine similarity between primary eigenvectors"
    )
    is_aligned: bool = Field(
        description="True if |cosine_similarity| > 0.90"
    )


# ─────────────────────────────────────────────────────────────
# Hypothesis & Claim Types
# ─────────────────────────────────────────────────────────────


class ClaimStatus(str, Enum):
    PROPOSED = "proposed"
    CONFIRMED = "confirmed"
    REFUTED = "refuted"
    NEEDS_MORE_DATA = "needs_more_data"


class HypothesisType(str, Enum):
    HYPER_RIBBON = "hyper_ribbon"
    UNIVERSAL_ALIGNMENT = "universal_alignment"
    SIMPSONS_PARADOX = "simpsons_paradox"
    PARAMETER_BOUND = "parameter_bound"
    MANIFOLD_EVOLUTION = "manifold_evolution"
    CAUSAL_MECHANISM = "causal_mechanism"


class Hypothesis(BaseModel):
    """A scientific hypothesis generated by the theorist agent."""

    hypothesis_id: str
    hypothesis_type: HypothesisType
    description: str = Field(description="Natural language statement of the hypothesis")
    testable_prediction: str = Field(
        description="A concrete, falsifiable prediction derived from this hypothesis"
    )
    required_experiments: list[str] = Field(
        description="Elements or potentials needed to test this hypothesis"
    )
    confidence: float = Field(ge=0.0, le=1.0)
    status: ClaimStatus = ClaimStatus.PROPOSED
    evidence_summary: Optional[str] = None


class ExperimentDesign(BaseModel):
    """A designed experiment to test a specific hypothesis."""

    experiment_id: str
    element: str
    potential_label: str
    pair_style: str
    structure: CrystalStructure
    discriminative_property: str = Field(
        description="The property most likely to distinguish this hypothesis"
    )
    test_strategy: str
    hypothesis_id: Optional[str] = None
    priority_score: float = Field(
        ge=0.0, le=1.0,
        description="Higher = more discriminative, should be tested first",
    )


class DiaryEntry(BaseModel):
    """A research diary entry summarizing findings from one analysis cycle."""

    element: str
    n_records: int
    n_potentials: int
    key_findings: list[str]
    open_questions: list[str]
    recommended_next: list[str]
