/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        'void-black': '#050508',
        'surface': '#0A0A12',
        'surface-elevated': '#10101C',
        'lupi-violet': '#7B5CFF',
        'lupi-violet-light': '#A08CFF',
        'lupi-cyan': '#00E5FF',
        'lupi-magenta': '#FF2E63',
        'text-primary': '#FFFFFF',
        'text-secondary': 'rgba(255, 255, 255, 0.6)',
        'text-tertiary': 'rgba(255, 255, 255, 0.3)',
        'cpk-h': '#FFFFFF',
        'cpk-c': '#909090',
        'cpk-n': '#3050F8',
        'cpk-o': '#FF0D0D',
        'cpk-f': '#90E050',
        'cpk-p': '#FF8000',
        'cpk-s': '#FFFF30',
        'cpk-cl': '#1FF01F',
        'cpk-fe': '#E06633',
        'cpk-cu': '#C78033',
        'cpk-zn': '#7D80B0',
      },
      fontFamily: {
        display: ['"Space Grotesk"', 'sans-serif'],
        body: ['"Inter"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'hero': ['72px', { lineHeight: '1.05', letterSpacing: '-2px', fontWeight: '300' }],
        'h2': ['48px', { lineHeight: '1.1', letterSpacing: '-1px', fontWeight: '300' }],
        'h3': ['32px', { lineHeight: '1.2', letterSpacing: '-0.5px', fontWeight: '500' }],
        'h4': ['20px', { lineHeight: '1.3', fontWeight: '500' }],
        'body': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'caption': ['12px', { lineHeight: '1.4', letterSpacing: '0.5px', fontWeight: '400' }],
        'code': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        'nav': ['13px', { lineHeight: '1', letterSpacing: '1px', fontWeight: '500' }],
        'button': ['14px', { lineHeight: '1', letterSpacing: '0.5px', fontWeight: '500' }],
      },
      spacing: {
        'section-desktop': '120px',
        'section-mobile': '64px',
        'content-px-desktop': '64px',
        'content-px-mobile': '24px',
      },
      maxWidth: {
        'content': '1400px',
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        'glow-violet': '0 0 20px rgba(123, 92, 255, 0.3)',
        'glow-cyan': '0 0 20px rgba(0, 229, 255, 0.3)',
        'glow-magenta': '0 0 20px rgba(255, 46, 99, 0.3)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "ticker-scroll": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "ticker-scroll": "ticker-scroll 30s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
