# Generated by generate_alloy_inputs.py
# Al-Cu fcc random solid solution, solute fraction 0.75
units		metal
variable	cfac equal 1.0e-4
variable	cunits string GPa
variable	up equal 1.0e-6
variable	atomjiggle equal 1.0e-5

variable	etol equal 0.0
variable	ftol equal 1.0e-10
variable	maxiter equal 100
variable	maxeval equal 1000
variable	dmax equal 1.0e-2

variable	a equal 3.723750

boundary	p p p
lattice		fcc $a
region		box block 0 4 0 4 0 4
create_box	2 box
create_atoms	1 box
set		type 1 type/fraction 2 0.75 12345
mass		1 26.982000
mass		2 63.546000
