/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SovereigntyRouteImport } from './routes/sovereignty'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProofRouteImport } from './routes/proof'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as LiveRouteImport } from './routes/live'
import { Route as InvestorRelationsRouteImport } from './routes/investor-relations'
import { Route as AtlasViewerRouteImport } from './routes/atlas-viewer'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SovereigntyRoute = SovereigntyRouteImport.update({
  id: '/sovereignty',
  path: '/sovereignty',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofRoute = ProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorRelationsRoute = InvestorRelationsRouteImport.update({
  id: '/investor-relations',
  path: '/investor-relations',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasViewerRoute = AtlasViewerRouteImport.update({
  id: '/atlas-viewer',
  path: '/atlas-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas-viewer': typeof AtlasViewerRoute
  '/investor-relations': typeof InvestorRelationsRoute
  '/live': typeof LiveRoute
  '/ops': typeof OpsRoute
  '/proof': typeof ProofRoute
  '/research': typeof ResearchRoute
  '/sovereignty': typeof SovereigntyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas-viewer': typeof AtlasViewerRoute
  '/investor-relations': typeof InvestorRelationsRoute
  '/live': typeof LiveRoute
  '/ops': typeof OpsRoute
  '/proof': typeof ProofRoute
  '/research': typeof ResearchRoute
  '/sovereignty': typeof SovereigntyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas-viewer': typeof AtlasViewerRoute
  '/investor-relations': typeof InvestorRelationsRoute
  '/live': typeof LiveRoute
  '/ops': typeof OpsRoute
  '/proof': typeof ProofRoute
  '/research': typeof ResearchRoute
  '/sovereignty': typeof SovereigntyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/atlas-viewer'
    | '/investor-relations'
    | '/live'
    | '/ops'
    | '/proof'
    | '/research'
    | '/sovereignty'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/atlas-viewer'
    | '/investor-relations'
    | '/live'
    | '/ops'
    | '/proof'
    | '/research'
    | '/sovereignty'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/atlas-viewer'
    | '/investor-relations'
    | '/live'
    | '/ops'
    | '/proof'
    | '/research'
    | '/sovereignty'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AtlasViewerRoute: typeof AtlasViewerRoute
  InvestorRelationsRoute: typeof InvestorRelationsRoute
  LiveRoute: typeof LiveRoute
  OpsRoute: typeof OpsRoute
  ProofRoute: typeof ProofRoute
  ResearchRoute: typeof ResearchRoute
  SovereigntyRoute: typeof SovereigntyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sovereignty': {
      id: '/sovereignty'
      path: '/sovereignty'
      fullPath: '/sovereignty'
      preLoaderRoute: typeof SovereigntyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof': {
      id: '/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof ProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor-relations': {
      id: '/investor-relations'
      path: '/investor-relations'
      fullPath: '/investor-relations'
      preLoaderRoute: typeof InvestorRelationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas-viewer': {
      id: '/atlas-viewer'
      path: '/atlas-viewer'
      fullPath: '/atlas-viewer'
      preLoaderRoute: typeof AtlasViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AtlasViewerRoute: AtlasViewerRoute,
  InvestorRelationsRoute: InvestorRelationsRoute,
  LiveRoute: LiveRoute,
  OpsRoute: OpsRoute,
  ProofRoute: ProofRoute,
  ResearchRoute: ResearchRoute,
  SovereigntyRoute: SovereigntyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
