/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlideshowRouteImport } from './routes/slideshow'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProofRouteImport } from './routes/proof'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as LiveRouteImport } from './routes/live'
import { Route as InvestorRelationsRouteImport } from './routes/investor-relations'
import { Route as EvolutionRouteImport } from './routes/evolution'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AtlasViewerRouteImport } from './routes/atlas-viewer'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SlideshowRoute = SlideshowRouteImport.update({
  id: '/slideshow',
  path: '/slideshow',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofRoute = ProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorRelationsRoute = InvestorRelationsRouteImport.update({
  id: '/investor-relations',
  path: '/investor-relations',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolutionRoute = EvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasViewerRoute = AtlasViewerRouteImport.update({
  id: '/atlas-viewer',
  path: '/atlas-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas-viewer': typeof AtlasViewerRoute
  '/console': typeof ConsoleRoute
  '/evolution': typeof EvolutionRoute
  '/investor-relations': typeof InvestorRelationsRoute
  '/live': typeof LiveRoute
  '/ops': typeof OpsRoute
  '/process': typeof ProcessRoute
  '/proof': typeof ProofRoute
  '/research': typeof ResearchRoute
  '/slideshow': typeof SlideshowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas-viewer': typeof AtlasViewerRoute
  '/console': typeof ConsoleRoute
  '/evolution': typeof EvolutionRoute
  '/investor-relations': typeof InvestorRelationsRoute
  '/live': typeof LiveRoute
  '/ops': typeof OpsRoute
  '/process': typeof ProcessRoute
  '/proof': typeof ProofRoute
  '/research': typeof ResearchRoute
  '/slideshow': typeof SlideshowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas-viewer': typeof AtlasViewerRoute
  '/console': typeof ConsoleRoute
  '/evolution': typeof EvolutionRoute
  '/investor-relations': typeof InvestorRelationsRoute
  '/live': typeof LiveRoute
  '/ops': typeof OpsRoute
  '/process': typeof ProcessRoute
  '/proof': typeof ProofRoute
  '/research': typeof ResearchRoute
  '/slideshow': typeof SlideshowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/atlas-viewer'
    | '/console'
    | '/evolution'
    | '/investor-relations'
    | '/live'
    | '/ops'
    | '/process'
    | '/proof'
    | '/research'
    | '/slideshow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/atlas-viewer'
    | '/console'
    | '/evolution'
    | '/investor-relations'
    | '/live'
    | '/ops'
    | '/process'
    | '/proof'
    | '/research'
    | '/slideshow'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/atlas-viewer'
    | '/console'
    | '/evolution'
    | '/investor-relations'
    | '/live'
    | '/ops'
    | '/process'
    | '/proof'
    | '/research'
    | '/slideshow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AtlasViewerRoute: typeof AtlasViewerRoute
  ConsoleRoute: typeof ConsoleRoute
  EvolutionRoute: typeof EvolutionRoute
  InvestorRelationsRoute: typeof InvestorRelationsRoute
  LiveRoute: typeof LiveRoute
  OpsRoute: typeof OpsRoute
  ProcessRoute: typeof ProcessRoute
  ProofRoute: typeof ProofRoute
  ResearchRoute: typeof ResearchRoute
  SlideshowRoute: typeof SlideshowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/slideshow': {
      id: '/slideshow'
      path: '/slideshow'
      fullPath: '/slideshow'
      preLoaderRoute: typeof SlideshowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof': {
      id: '/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof ProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor-relations': {
      id: '/investor-relations'
      path: '/investor-relations'
      fullPath: '/investor-relations'
      preLoaderRoute: typeof InvestorRelationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolution': {
      id: '/evolution'
      path: '/evolution'
      fullPath: '/evolution'
      preLoaderRoute: typeof EvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas-viewer': {
      id: '/atlas-viewer'
      path: '/atlas-viewer'
      fullPath: '/atlas-viewer'
      preLoaderRoute: typeof AtlasViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AtlasViewerRoute: AtlasViewerRoute,
  ConsoleRoute: ConsoleRoute,
  EvolutionRoute: EvolutionRoute,
  InvestorRelationsRoute: InvestorRelationsRoute,
  LiveRoute: LiveRoute,
  OpsRoute: OpsRoute,
  ProcessRoute: ProcessRoute,
  ProofRoute: ProofRoute,
  ResearchRoute: ResearchRoute,
  SlideshowRoute: SlideshowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
