import type { Atom, MoleculeData } from '@/components/MoleculeViewer';
import { getAtomicWeight } from './elements';

// ============================
// XYZ Parsing
// ============================
export function parseXYZ(xyzText: string): MoleculeData | null {
  const lines = xyzText.trim().split('\n').map(l => l.trim()).filter(Boolean);
  if (lines.length < 3) return null;

  const atomCount = parseInt(lines[0], 10);
  if (isNaN(atomCount) || atomCount <= 0 || atomCount > 10000) return null;

  const atoms: Atom[] = [];
  for (let i = 2; i < lines.length && atoms.length < atomCount; i++) {
    const parts = lines[i].trim().split(/\s+/);
    if (parts.length >= 4) {
      const element = parts[0];
      const x = parseFloat(parts[1]);
      const y = parseFloat(parts[2]);
      const z = parseFloat(parts[3]);
      if (!isNaN(x) && !isNaN(y) && !isNaN(z)) {
        atoms.push({ element, x, y, z });
      }
    }
  }

  if (atoms.length === 0) return null;
  return { atoms };
}

// ============================
// SDF Parsing (simplified)
// ============================
export function parseSDF(sdfText: string): MoleculeData | null {
  const lines = sdfText.split('\n');
  if (lines.length < 5) return null;

  // Line 4: atom count (first 3 chars), bond count (chars 4-6)
  const line4 = lines[3];
  const atomCount = parseInt(line4.substring(0, 3).trim(), 10);
  if (isNaN(atomCount) || atomCount <= 0 || atomCount > 10000) return null;

  const atoms: Atom[] = [];
  for (let i = 0; i < atomCount; i++) {
    const line = lines[4 + i];
    if (!line || line.length < 30) continue;

    const x = parseFloat(line.substring(0, 10).trim());
    const y = parseFloat(line.substring(10, 20).trim());
    const z = parseFloat(line.substring(20, 30).trim());
    const element = line.substring(30, 34).trim();

    if (!isNaN(x) && !isNaN(y) && !isNaN(z) && element) {
      atoms.push({ element, x, y, z });
    }
  }

  if (atoms.length === 0) return null;
  return { atoms };
}

// Convert atoms to XYZ format string
export function atomsToXYZ(atoms: Atom[], title = 'Generated by LUPI'): string {
  const lines = [String(atoms.length), title];
  for (const atom of atoms) {
    const { element, x, y, z } = atom;
    lines.push(`${element.padEnd(4)} ${x.toFixed(6).padStart(12)} ${y.toFixed(6).padStart(12)} ${z.toFixed(6).padStart(12)}`);
  }
  return lines.join('\n');
}

// ============================
// PubChem API Integration
// ============================
export async function fetchMoleculeFromPubChemByName(name: string): Promise<{ moleculeData: MoleculeData; cid?: string; formula?: string }> {
  const url = `https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/${encodeURIComponent(name)}/record/SDF/?record_type=3d`;
  const response = await fetch(url);

  if (!response.ok) {
    if (response.status === 404) {
      throw new Error(`Molecule "${name}" not found in PubChem. Try a different name or use SMILES notation.`);
    }
    throw new Error(`PubChem API error: ${response.statusText}`);
  }

  const sdfText = await response.text();
  const moleculeData = parseSDF(sdfText);

  if (!moleculeData) {
    throw new Error('Failed to parse SDF data from PubChem.');
  }

  return { moleculeData };
}

export async function fetchMoleculeFromPubChemBySMILES(smiles: string): Promise<{ moleculeData: MoleculeData; cid?: string; formula?: string }> {
  const url = `https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/smiles/${encodeURIComponent(smiles)}/record/SDF/?record_type=3d`;
  const response = await fetch(url);

  if (!response.ok) {
    if (response.status === 404) {
      throw new Error(`SMILES string not recognized by PubChem. Check the notation and try again.`);
    }
    throw new Error(`PubChem API error: ${response.statusText}`);
  }

  const sdfText = await response.text();
  const moleculeData = parseSDF(sdfText);

  if (!moleculeData) {
    throw new Error('Failed to parse SDF data from PubChem.');
  }

  return { moleculeData };
}

// ============================
// Molecular Formula Calculation
// ============================
export function calculateFormula(atoms: Atom[]): string {
  const counts: Record<string, number> = {};
  for (const atom of atoms) {
    counts[atom.element] = (counts[atom.element] || 0) + 1;
  }

  // Order: C, H, then rest alphabetically
  const elements = Object.keys(counts).sort((a, b) => {
    if (a === 'C') return -1;
    if (b === 'C') return 1;
    if (a === 'H') return -1;
    if (b === 'H') return 1;
    return a.localeCompare(b);
  });

  return elements.map(el => {
    const count = counts[el];
    return count > 1 ? `${el}${count}` : el;
  }).join('');
}

export function calculateMolecularWeight(atoms: Atom[]): number {
  let weight = 0;
  for (const atom of atoms) {
    weight += getAtomicWeight(atom.element);
  }
  return Math.round(weight * 100) / 100;
}

export function getAtomCounts(atoms: Atom[]): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const atom of atoms) {
    counts[atom.element] = (counts[atom.element] || 0) + 1;
  }
  return counts;
}

// ============================
// History Entry Type
// ============================
export interface HistoryEntry {
  id: string;
  name: string;
  formula: string;
  atoms: Atom[];
  source: 'PubChem' | 'AI' | 'Manual';
  timestamp: number;
  smiles?: string;
}

// ============================
// Popular Molecule Templates
// ============================
export interface MoleculeTemplate {
  name: string;
  smiles?: string;
  data: MoleculeData;
  description?: string;
  tags?: string[];
}

// Popular molecules with realistic XYZ data
export const POPULAR_MOLECULES: MoleculeTemplate[] = [
  {
    name: 'Caffeine',
    smiles: 'CN1C=NC2=C1C(=O)N(C(=O)N2C)C',
    description: 'The world\'s favorite stimulant',
    tags: ['alkaloid', 'stimulant'],
    data: {
      atoms: [
        { element: 'C', x: 1.028, y: -0.063, z: -0.111 },
        { element: 'N', x: 2.396, y: 0.141, z: -0.069 },
        { element: 'C', x: 3.081, y: -0.954, z: -0.672 },
        { element: 'N', x: 2.419, y: -1.972, z: -1.224 },
        { element: 'C', x: 1.081, y: -1.853, z: -1.092 },
        { element: 'C', x: 0.316, y: -2.892, z: -1.572 },
        { element: 'O', x: -0.889, y: -2.770, z: -1.514 },
        { element: 'N', x: 0.437, y: -0.764, z: -0.589 },
        { element: 'C', x: 0.888, y: 0.533, z: 1.282 },
        { element: 'O', x: 2.800, y: 1.108, z: 0.533 },
        { element: 'C', x: 4.477, y: 0.508, z: 0.398 },
        { element: 'C', x: 3.064, y: -0.753, z: -2.787 },
        { element: 'C', x: -0.831, y: -0.416, z: -0.684 },
        { element: 'C', x: -1.184, y: 0.962, z: -0.233 },
        { element: 'H', x: -0.871, y: 1.712, z: -0.981 },
        { element: 'H', x: -0.729, y: 1.251, z: 0.726 },
        { element: 'H', x: -2.267, y: 1.021, z: -0.109 },
        { element: 'H', x: 0.408, y: -0.117, z: 1.864 },
        { element: 'H', x: 0.706, y: 1.502, z: 1.762 },
        { element: 'H', x: 1.965, y: 0.439, z: 1.433 },
        { element: 'H', x: 4.735, y: 1.445, z: 0.900 },
        { element: 'H', x: 4.658, y: 0.640, z: -0.674 },
        { element: 'H', x: 5.133, y: -0.261, z: 0.753 },
        { element: 'H', x: 2.544, y: -1.599, z: -3.250 },
      ],
    },
  },
  {
    name: 'Aspirin',
    smiles: 'CC(=O)Oc1ccccc1C(=O)O',
    description: 'Acetylsalicylic acid — pain relief',
    tags: ['analgesic', 'NSAID'],
    data: {
      atoms: [
        { element: 'C', x: -0.528, y: 1.228, z: 0.104 },
        { element: 'C', x: 0.848, y: 1.197, z: 0.266 },
        { element: 'C', x: 1.526, y: 0.009, z: 0.125 },
        { element: 'C', x: 0.828, y: -1.148, z: -0.177 },
        { element: 'C', x: -0.548, y: -1.117, z: -0.339 },
        { element: 'C', x: -1.226, y: 0.075, z: -0.198 },
        { element: 'C', x: -2.695, y: 0.107, z: -0.371 },
        { element: 'O', x: -3.227, y: 1.185, z: -0.608 },
        { element: 'O', x: -3.329, y: -1.046, z: -0.231 },
        { element: 'C', x: -4.740, y: -0.964, z: -0.384 },
        { element: 'O', x: 1.540, y: 2.285, z: 0.551 },
        { element: 'C', x: 2.940, y: 2.254, z: 0.713 },
        { element: 'C', x: 3.471, y: 3.332, z: 0.999 },
        { element: 'O', x: 3.523, y: 1.138, z: 0.573 },
        { element: 'H', x: -1.057, y: 2.155, z: 0.213 },
        { element: 'H', x: 2.601, y: 0.015, z: 0.250 },
        { element: 'H', x: 1.353, y: -2.075, z: -0.286 },
        { element: 'H', x: -1.082, y: -2.014, z: -0.571 },
        { element: 'H', x: -4.996, y: -0.487, z: -1.329 },
        { element: 'H', x: -5.105, y: -1.989, z: -0.280 },
        { element: 'H', x: -5.179, y: -0.415, z: 0.451 },
      ],
    },
  },
  {
    name: 'Dopamine',
    smiles: 'C1=CC(=C(C=C1CCN)O)O',
    description: 'Neurotransmitter of reward and pleasure',
    tags: ['neurotransmitter', 'amine'],
    data: {
      atoms: [
        { element: 'C', x: 0.041, y: 0.118, z: 0.007 },
        { element: 'C', x: 1.421, y: 0.248, z: 0.143 },
        { element: 'C', x: 2.147, y: -0.933, z: 0.318 },
        { element: 'C', x: 1.493, y: -2.172, z: 0.356 },
        { element: 'C', x: 0.113, y: -2.229, z: 0.220 },
        { element: 'C', x: -0.614, y: -1.058, z: 0.045 },
        { element: 'O', x: -0.456, y: 1.265, z: -0.168 },
        { element: 'O', x: -0.541, y: -3.348, z: 0.257 },
        { element: 'C', x: 3.613, y: -0.876, z: 0.464 },
        { element: 'C', x: 4.299, y: -2.057, z: 0.639 },
        { element: 'N', x: 5.657, y: -2.000, z: 0.785 },
        { element: 'H', x: 1.927, y: 1.208, z: 0.113 },
        { element: 'H', x: 2.074, y: -3.088, z: 0.493 },
        { element: 'H', x: -1.689, y: -1.100, z: -0.059 },
        { element: 'H', x: -1.518, y: -3.312, z: 0.158 },
        { element: 'H', x: 3.847, y: -0.005, z: 0.434 },
        { element: 'H', x: 3.924, y: -2.968, z: 0.669 },
        { element: 'H', x: 5.996, y: -2.936, z: 0.870 },
        { element: 'H', x: 6.177, y: -1.180, z: 0.755 },
      ],
    },
  },
  {
    name: 'Serotonin',
    smiles: 'C1=CC2=C(C=C1O)C(=CN2)CCN',
    description: 'The mood-regulating neurotransmitter',
    tags: ['neurotransmitter', 'indole'],
    data: {
      atoms: [
        { element: 'C', x: -0.194, y: 0.406, z: -0.028 },
        { element: 'C', x: 0.721, y: 1.457, z: 0.035 },
        { element: 'C', x: 2.102, y: 1.260, z: 0.157 },
        { element: 'C', x: 2.565, y: -0.058, z: 0.216 },
        { element: 'C', x: 1.649, y: -1.115, z: 0.153 },
        { element: 'C', x: 0.268, y: -0.918, z: 0.031 },
        { element: 'N', x: 2.978, y: 2.291, z: 0.220 },
        { element: 'C', x: 4.296, y: 1.908, z: 0.341 },
        { element: 'C', x: 4.352, y: 0.540, z: 0.400 },
        { element: 'C', x: 3.152, y: -0.202, z: 0.338 },
        { element: 'O', x: -1.534, y: 0.603, z: -0.148 },
        { element: 'C', x: 1.785, y: -2.548, z: 0.215 },
        { element: 'C', x: 2.963, y: -3.280, z: 0.277 },
        { element: 'N', x: 3.965, y: -2.899, z: 0.338 },
        { element: 'H', x: 0.372, y: 2.482, z: -0.009 },
        { element: 'H', x: 3.181, y: 3.257, z: 0.202 },
        { element: 'H', x: 5.165, y: 2.549, z: 0.389 },
        { element: 'H', x: 5.274, y: 0.030, z: 0.496 },
        { element: 'H', x: -2.035, y: -0.225, z: -0.241 },
        { element: 'H', x: 1.082, y: -3.058, z: 0.215 },
        { element: 'H', x: 3.061, y: -4.364, z: 0.325 },
        { element: 'H', x: 4.912, y: -3.349, z: 0.415 },
      ],
    },
  },
  {
    name: 'THC',
    smiles: 'CCCCCCc1cc(O)c2c(c1)OC(C)(C)[C@@H]1CCC(C)=C[C@@H]21',
    description: 'Delta-9-tetrahydrocannabinol',
    tags: ['cannabinoid', 'psychoactive'],
    data: {
      atoms: [
        { element: 'C', x: -1.223, y: -0.847, z: -0.268 },
        { element: 'C', x: -0.025, y: -0.163, z: 0.169 },
        { element: 'C', x: -0.143, y: 1.307, z: 0.437 },
        { element: 'C', x: -1.459, y: 1.793, z: 0.237 },
        { element: 'C', x: -2.539, y: 1.064, z: -0.169 },
        { element: 'C', x: -2.424, y: -0.312, z: -0.437 },
        { element: 'O', x: 0.904, y: 1.944, z: 0.825 },
        { element: 'C', x: 1.233, y: -0.763, z: 0.360 },
        { element: 'C', x: 2.448, y: -0.214, z: 0.793 },
        { element: 'C', x: 2.567, y: 1.148, z: 1.061 },
        { element: 'C', x: 1.471, y: 2.026, z: 0.897 },
        { element: 'C', x: 1.088, y: -2.213, z: 0.092 },
        { element: 'C', x: -3.586, y: -1.112, z: -0.877 },
        { element: 'C', x: 3.620, y: -1.152, z: 0.979 },
        { element: 'C', x: 3.832, y: 1.749, z: 1.506 },
        { element: 'C', x: 0.854, y: -3.025, z: 1.182 },
        { element: 'C', x: 2.342, y: -2.824, z: -0.654 },
        { element: 'O', x: -0.078, y: -2.463, z: -0.833 },
        { element: 'C', x: 0.560, y: 3.381, z: 1.163 },
        { element: 'C', x: -3.774, y: 1.692, z: -0.355 },
        { element: 'C', x: -4.876, y: 0.933, z: -0.741 },
        { element: 'C', x: -4.758, y: -0.441, z: -1.009 },
        { element: 'C', x: -5.919, y: -1.225, z: -1.437 },
        { element: 'H', x: -1.130, y: -1.915, z: -0.473 },
        { element: 'H', x: -1.555, y: 2.861, z: 0.442 },
        { element: 'H', x: 1.139, y: -0.524, z: 1.424 },
        { element: 'H', x: -3.506, y: -2.180, z: -1.082 },
        { element: 'H', x: 3.535, y: -1.568, z: 1.981 },
        { element: 'H', x: 4.562, y: -0.721, z: 0.810 },
        { element: 'H', x: 3.752, y: -1.993, z: 0.300 },
        { element: 'H', x: 4.722, y: 1.179, z: 1.255 },
        { element: 'H', x: 3.882, y: 1.857, z: 2.594 },
        { element: 'H', x: 3.875, y: 2.740, z: 1.051 },
        { element: 'H', x: 0.163, y: -2.712, z: 1.948 },
        { element: 'H', x: 1.791, y: -3.239, z: 1.625 },
        { element: 'H', x: 0.515, y: -4.060, z: 0.852 },
        { element: 'H', x: 2.483, y: -3.609, z: -1.402 },
        { element: 'H', x: 2.969, y: -3.063, z: 0.207 },
        { element: 'H', x: 2.816, y: -1.970, z: -1.147 },
        { element: 'H', x: 1.121, y: 3.977, z: 1.397 },
        { element: 'H', x: -0.053, y: 3.352, z: 2.061 },
        { element: 'H', x: 0.007, y: 3.856, z: 0.343 },
        { element: 'H', x: -3.862, y: 2.760, z: -0.152 },
        { element: 'H', x: -5.842, y: 1.420, z: -0.888 },
        { element: 'H', x: -5.810, y: -1.620, z: -2.442 },
        { element: 'H', x: -6.294, y: -2.027, z: -0.792 },
        { element: 'H', x: -6.705, y: -0.553, z: -1.473 },
      ],
    },
  },
  {
    name: 'LSD',
    smiles: 'CCN(CC)C(=O)[C@@H]1C=C2c3cccc4[nH]cc(c34)C[C@H]2C[C@@H]1OC(=O)C',
    description: 'Lysergic acid diethylamide',
    tags: ['psychedelic', 'ergoline'],
    data: {
      atoms: [
        { element: 'C', x: -1.856, y: 0.543, z: -0.301 },
        { element: 'C', x: -0.528, y: 0.936, z: -0.019 },
        { element: 'C', x: 0.478, y: -0.024, z: 0.155 },
        { element: 'C', x: 0.079, y: -1.378, z: 0.048 },
        { element: 'C', x: -1.249, y: -1.771, z: -0.235 },
        { element: 'C', x: -2.255, y: -0.811, z: -0.409 },
        { element: 'N', x: 1.780, y: 0.369, z: 0.438 },
        { element: 'C', x: 2.786, y: -0.591, z: 0.613 },
        { element: 'C', x: 2.387, y: -1.945, z: 0.506 },
        { element: 'C', x: 1.085, y: -2.338, z: 0.223 },
        { element: 'C', x: 2.242, y: 1.723, z: 0.544 },
        { element: 'C', x: 3.543, y: 2.116, z: 0.827 },
        { element: 'C', x: 4.549, y: 1.156, z: 1.002 },
        { element: 'N', x: 4.150, y: -0.198, z: 0.895 },
        { element: 'C', x: -0.127, y: 2.379, z: 0.098 },
        { element: 'N', x: 1.206, y: 2.772, z: 0.381 },
        { element: 'C', x: 3.932, y: 3.470, z: 0.950 },
        { element: 'C', x: 3.128, y: -2.905, z: 0.681 },
        { element: 'O', x: -0.927, y: 3.115, z: -0.033 },
        { element: 'C', x: 5.935, y: 1.549, z: 1.285 },
        { element: 'N', x: 1.483, y: 4.122, z: 0.487 },
        { element: 'C', x: 0.332, y: 4.766, z: 0.272 },
        { element: 'C', x: -0.784, y: 4.066, z: -0.043 },
        { element: 'C', x: 0.172, y: 6.243, z: 0.396 },
        { element: 'H', x: -2.636, y: 1.293, z: -0.439 },
        { element: 'H', x: 1.013, y: -3.388, z: 0.140 },
        { element: 'H', x: 2.915, y: 2.349, z: -0.245 },
        { element: 'H', x: 4.898, y: -0.834, z: 1.032 },
        { element: 'H', x: 4.737, y: 4.103, z: 1.164 },
        { element: 'H', x: 3.336, y: -3.955, z: 0.598 },
        { element: 'H', x: 6.233, y: 2.165, z: 0.436 },
        { element: 'H', x: 6.076, y: 2.118, z: 2.209 },
        { element: 'H', x: 6.563, y: 0.664, z: 1.339 },
        { element: 'H', x: 2.377, y: 4.621, z: 0.728 },
        { element: 'H', x: -1.765, y: 4.505, z: -0.207 },
        { element: 'H', x: -0.764, y: 6.424, z: 0.229 },
        { element: 'H', x: 0.381, y: 6.639, z: 1.394 },
        { element: 'H', x: 0.828, y: 6.730, z: -0.330 },
      ],
    },
  },
  {
    name: 'Psilocybin',
    smiles: 'CN(C)CCC1=CNC2=C1C(=CC=C2)OP(=O)(O)O',
    description: 'Psychedelic compound in magic mushrooms',
    tags: ['psychedelic', 'tryptamine'],
    data: {
      atoms: [
        { element: 'C', x: 0.014, y: 0.042, z: -0.003 },
        { element: 'C', x: 1.403, y: 0.354, z: 0.134 },
        { element: 'C', x: 2.108, y: -0.831, z: 0.441 },
        { element: 'C', x: 1.424, y: -2.019, z: 0.611 },
        { element: 'C', x: 0.035, y: -1.931, z: 0.474 },
        { element: 'C', x: -0.670, y: -0.746, z: 0.167 },
        { element: 'N', x: -0.672, y: 1.227, z: -0.293 },
        { element: 'C', x: -2.060, y: 1.139, z: -0.430 },
        { element: 'C', x: -2.766, y: -0.046, z: -0.137 },
        { element: 'C', x: -2.081, y: -1.234, z: 0.033 },
        { element: 'N', x: 2.092, y: 1.542, z: 0.003 },
        { element: 'C', x: 3.455, y: 1.854, z: 0.140 },
        { element: 'C', x: 4.160, y: 0.669, z: 0.447 },
        { element: 'C', x: 3.477, y: -0.519, z: 0.617 },
        { element: 'O', x: 1.503, y: 2.597, z: -0.280 },
        { element: 'P', x: 0.663, y: -3.478, z: 0.824 },
        { element: 'O', x: -0.404, y: -3.390, z: -0.214 },
        { element: 'O', x: -0.103, y: -3.612, z: 2.119 },
        { element: 'O', x: 1.314, y: -4.837, z: 0.674 },
        { element: 'C', x: -2.595, y: 2.434, z: -0.796 },
        { element: 'N', x: -4.125, y: 0.042, z: -0.060 },
        { element: 'C', x: -4.738, y: -1.095, z: -0.379 },
        { element: 'C', x: -4.082, y: 1.281, z: 0.259 },
        { element: 'H', x: 3.748, y: -1.451, z: 0.859 },
        { element: 'H', x: 5.239, y: 0.670, z: 0.553 },
        { element: 'H', x: 3.912, y: 2.834, z: 0.003 },
        { element: 'H', x: -3.124, y: 2.364, z: -1.753 },
        { element: 'H', x: -1.957, y: 3.311, z: -0.857 },
        { element: 'H', x: -3.315, y: 2.588, z: -0.000 },
        { element: 'H', x: -5.818, y: -1.037, z: -0.293 },
        { element: 'H', x: -4.425, y: -2.021, z: -0.855 },
        { element: 'H', x: -4.449, y: 2.095, z: 0.485 },
        { element: 'H', x: -0.280, y: 2.141, z: -0.460 },
      ],
    },
  },
  {
    name: 'Cholesterol',
    smiles: 'CC(C)CCCC(C)C1CCC2C1(CCC3C2CC=C4C3(CCC(C4)O)C)C',
    description: 'Essential sterol lipid',
    tags: ['sterol', 'lipid'],
    data: {
      atoms: [
        { element: 'C', x: -1.542, y: 0.826, z: -0.312 },
        { element: 'C', x: -0.120, y: 0.458, z: 0.094 },
        { element: 'C', x: 0.881, y: 1.475, z: -0.286 },
        { element: 'C', x: 0.553, y: 2.799, z: 0.345 },
        { element: 'C', x: -0.869, y: 3.167, z: -0.061 },
        { element: 'C', x: -1.870, y: 2.150, z: 0.319 },
        { element: 'C', x: 0.247, y: -0.866, z: -0.537 },
        { element: 'C', x: 1.548, y: -1.234, z: -0.133 },
        { element: 'C', x: 1.876, y: -2.558, z: 0.498 },
        { element: 'C', x: 0.902, y: -3.575, z: 0.118 },
        { element: 'C', x: -0.399, y: -3.207, z: -0.286 },
        { element: 'C', x: -0.727, y: -1.883, z: -0.917 },
        { element: 'C', x: -1.723, y: -3.504, z: -0.610 },
        { element: 'C', x: -2.051, y: -2.180, z: -1.241 },
        { element: 'C', x: 1.230, y: -4.899, z: 0.749 },
        { element: 'C', x: -2.487, y: -0.957, z: -1.065 },
        { element: 'C', x: 2.542, y: -0.217, z: -0.513 },
        { element: 'C', x: 3.843, y: -0.585, z: -0.109 },
        { element: 'C', x: 4.171, y: -1.909, z: 0.522 },
        { element: 'C', x: 3.197, y: -2.926, z: 0.142 },
        { element: 'C', x: 2.870, y: 1.107, z: -1.144 },
        { element: 'C', x: 4.292, y: 0.432, z: 0.522 },
        { element: 'C', x: 4.620, y: 1.756, z: -0.109 },
        { element: 'C', x: 3.646, y: 2.773, z: -0.489 },
        { element: 'C', x: 2.344, y: 2.405, z: -0.893 },
        { element: 'O', x: 5.905, y: 2.124, z: 0.295 },
        { element: 'C', x: -3.517, y: -4.118, z: -0.538 },
        { element: 'C', x: -3.105, y: -0.179, z: -0.385 },
        { element: 'C', x: 3.838, y: 4.097, z: -0.120 },
        { element: 'C', x: 1.524, y: -5.881, z: -0.371 },
        { element: 'H', x: -1.870, y: 0.786, z: -1.355 },
        { element: 'H', x: -2.316, y: 0.186, z: -0.023 },
        { element: 'H', x: 0.801, y: 1.515, z: -1.376 },
        { element: 'H', x: 1.269, y: 3.545, z: 0.065 },
        { element: 'H', x: 0.545, y: 2.759, z: 1.437 },
        { element: 'H', x: -1.097, y: 3.207, z: -1.130 },
        { element: 'H', x: -2.889, y: 2.430, z: 0.032 },
        { element: 'H', x: 0.339, y: -0.906, z: -1.629 },
        { element: 'H', x: 1.824, y: -2.518, z: 1.590 },
        { element: 'H', x: 0.838, y: -4.939, z: 1.791 },
        { element: 'H', x: 1.791, y: -0.194, z: -1.605 },
        { element: 'H', x: 4.470, y: 0.392, z: 1.614 },
        { element: 'H', x: 2.607, y: 1.147, z: -2.236 },
        { element: 'H', x: 1.979, y: 3.151, z: -1.244 },
        { element: 'H', x: 6.072, y: 2.994, z: -0.056 },
        { element: 'H', x: -4.256, y: -3.489, z: -0.977 },
        { element: 'H', x: -3.508, y: -4.279, z: 0.543 },
        { element: 'H', x: -3.687, y: -5.085, z: -0.949 },
        { element: 'H', x: -3.262, y: 0.821, z: -0.720 },
        { element: 'H', x: -3.621, y: -0.439, z: 0.534 },
        { element: 'H', x: -3.692, y: -0.023, z: 1.237 },
        { element: 'H', x: 4.417, y: 4.737, z: -0.558 },
        { element: 'H', x: 3.746, y: 4.257, z: 0.962 },
        { element: 'H', x: 2.830, y: -4.286, z: 0.483 },
        { element: 'H', x: 4.271, y: -2.189, z: -0.410 },
        { element: 'H', x: 2.091, y: -3.317, z: 1.234 },
        { element: 'H', x: 1.291, y: -5.376, z: -1.325 },
        { element: 'H', x: 0.734, y: -6.630, z: -0.221 },
        { element: 'H', x: 2.464, y: -6.390, z: -0.419 },
      ],
    },
  },
  {
    name: 'Water',
    smiles: 'O',
    description: 'The molecule of life',
    tags: ['solvent', 'essential'],
    data: {
      atoms: [
        { element: 'O', x: 0.000, y: 0.000, z: 0.000 },
        { element: 'H', x: 0.757, y: 0.586, z: 0.000 },
        { element: 'H', x: -0.757, y: 0.586, z: 0.000 },
      ],
    },
  },
  {
    name: 'Benzene',
    smiles: 'c1ccccc1',
    description: 'The aromatic ring — foundation of organic chemistry',
    tags: ['aromatic', 'organic'],
    data: {
      atoms: [
        { element: 'C', x: 1.390, y: 0.000, z: 0.000 },
        { element: 'C', x: 0.695, y: 1.204, z: 0.000 },
        { element: 'C', x: -0.695, y: 1.204, z: 0.000 },
        { element: 'C', x: -1.390, y: 0.000, z: 0.000 },
        { element: 'C', x: -0.695, y: -1.204, z: 0.000 },
        { element: 'C', x: 0.695, y: -1.204, z: 0.000 },
        { element: 'H', x: 2.470, y: 0.000, z: 0.000 },
        { element: 'H', x: 1.235, y: 2.139, z: 0.000 },
        { element: 'H', x: -1.235, y: 2.139, z: 0.000 },
        { element: 'H', x: -2.470, y: 0.000, z: 0.000 },
        { element: 'H', x: -1.235, y: -2.139, z: 0.000 },
        { element: 'H', x: 1.235, y: -2.139, z: 0.000 },
      ],
    },
  },
  {
    name: 'Methane',
    smiles: 'C',
    description: 'The simplest hydrocarbon',
    tags: ['alkane', 'fuel'],
    data: {
      atoms: [
        { element: 'C', x: 0.000, y: 0.000, z: 0.000 },
        { element: 'H', x: 0.629, y: 0.629, z: 0.629 },
        { element: 'H', x: -0.629, y: -0.629, z: 0.629 },
        { element: 'H', x: -0.629, y: 0.629, z: -0.629 },
        { element: 'H', x: 0.629, y: -0.629, z: -0.629 },
      ],
    },
  },
  {
    name: 'Ethanol',
    smiles: 'CCO',
    description: 'The intoxicating alcohol',
    tags: ['alcohol', 'solvent'],
    data: {
      atoms: [
        { element: 'C', x: -0.515, y: 0.024, z: 0.000 },
        { element: 'C', x: 0.972, y: -0.028, z: 0.000 },
        { element: 'O', x: 1.470, y: 1.264, z: 0.000 },
        { element: 'H', x: -0.861, y: 1.059, z: 0.000 },
        { element: 'H', x: -0.861, y: -0.496, z: 0.890 },
        { element: 'H', x: -0.861, y: -0.496, z: -0.890 },
        { element: 'H', x: 1.318, y: -0.558, z: 0.890 },
        { element: 'H', x: 1.318, y: -0.558, z: -0.890 },
        { element: 'H', x: 2.431, y: 1.237, z: 0.000 },
      ],
    },
  },
  {
    name: 'Diamond',
    description: 'Carbon in sp3 tetrahedral lattice (unit cell)',
    tags: ['mineral', 'allotrope'],
    data: {
      atoms: [
        { element: 'C', x: 0.000, y: 0.000, z: 0.000 },
        { element: 'C', x: 0.893, y: 0.893, z: 0.893 },
        { element: 'C', x: 1.786, y: 0.000, z: 1.786 },
        { element: 'C', x: 2.679, y: 0.893, z: 2.679 },
        { element: 'C', x: 0.000, y: 1.786, z: 1.786 },
        { element: 'C', x: 0.893, y: 2.679, z: 2.679 },
        { element: 'C', x: 1.786, y: 1.786, z: 0.000 },
        { element: 'C', x: 2.679, y: 2.679, z: 0.893 },
        { element: 'C', x: 0.893, y: 0.000, z: 2.679 },
        { element: 'C', x: 0.000, y: 0.893, z: 1.786 },
        { element: 'C', x: 2.679, y: 0.000, z: 0.893 },
        { element: 'C', x: 1.786, y: 0.893, z: 0.000 },
        { element: 'C', x: 0.893, y: 1.786, z: 1.786 },
        { element: 'C', x: 0.000, y: 2.679, z: 0.893 },
        { element: 'C', x: 2.679, y: 1.786, z: 2.679 },
        { element: 'C', x: 1.786, y: 2.679, z: 1.786 },
        { element: 'C', x: 0.893, y: 0.893, z: 3.572 },
        { element: 'C', x: 0.000, y: 0.000, z: 2.679 },
      ],
    },
  },
  {
    name: 'Buckminsterfullerene',
    description: 'C60 — the spherical carbon molecule',
    tags: ['fullerene', 'nanomaterial'],
    data: {
      atoms: [
        { element: 'C', x: 1.213, y: 0.412, z: 3.489 },
        { element: 'C', x: 0.749, y: 1.213, z: 3.489 },
        { element: 'C', x: -0.412, y: 1.213, z: 3.489 },
        { element: 'C', x: -1.213, y: 0.749, z: 3.489 },
        { element: 'C', x: -1.213, y: -0.412, z: 3.489 },
        { element: 'C', x: -0.749, y: -1.213, z: 3.489 },
        { element: 'C', x: 0.412, y: -1.213, z: 3.489 },
        { element: 'C', x: 1.213, y: -0.749, z: 3.489 },
        { element: 'C', x: 2.427, y: 0.412, z: 2.789 },
        { element: 'C', x: 1.498, y: 1.498, z: 2.789 },
        { element: 'C', x: -0.000, y: 1.890, z: 2.789 },
        { element: 'C', x: -1.498, y: 1.498, z: 2.789 },
        { element: 'C', x: -2.427, y: 0.412, z: 2.789 },
        { element: 'C', x: -2.427, y: -0.412, z: 2.789 },
        { element: 'C', x: -1.498, y: -1.498, z: 2.789 },
        { element: 'C', x: -0.000, y: -1.890, z: 2.789 },
        { element: 'C', x: 1.498, y: -1.498, z: 2.789 },
        { element: 'C', x: 2.427, y: -0.412, z: 2.789 },
        { element: 'C', x: 2.789, y: 1.498, z: 1.890 },
        { element: 'C', x: 2.789, y: 0.000, z: 1.890 },
        { element: 'C', x: 2.789, y: -1.498, z: 1.890 },
        { element: 'C', x: 1.890, y: -2.427, z: 1.890 },
        { element: 'C', x: 0.412, y: -2.789, z: 1.890 },
        { element: 'C', x: -1.213, y: -2.427, z: 1.890 },
        { element: 'C', x: -2.427, y: -1.498, z: 1.890 },
        { element: 'C', x: -2.789, y: -0.000, z: 1.890 },
        { element: 'C', x: -2.789, y: 1.498, z: 1.890 },
        { element: 'C', x: -1.890, y: 2.427, z: 1.890 },
        { element: 'C', x: -0.412, y: 2.789, z: 1.890 },
        { element: 'C', x: 1.213, y: 2.427, z: 1.890 },
        { element: 'C', x: 1.890, y: 2.427, z: 1.890 },
        { element: 'C', x: 3.489, y: 1.213, z: 0.749 },
        { element: 'C', x: 3.489, y: -0.749, z: 0.749 },
        { element: 'C', x: 2.789, y: -2.427, z: 0.749 },
        { element: 'C', x: 1.213, y: -3.489, z: 0.749 },
        { element: 'C', x: -1.213, y: -3.489, z: 0.749 },
        { element: 'C', x: -2.789, y: -2.427, z: 0.749 },
        { element: 'C', x: -3.489, y: -0.749, z: 0.749 },
        { element: 'C', x: -3.489, y: 1.213, z: 0.749 },
        { element: 'C', x: -2.789, y: 2.427, z: 0.749 },
        { element: 'C', x: -1.213, y: 3.489, z: 0.749 },
        { element: 'C', x: 1.213, y: 3.489, z: 0.749 },
        { element: 'C', x: 2.789, y: 2.427, z: 0.749 },
        { element: 'C', x: 3.489, y: 1.213, z: -0.749 },
        { element: 'C', x: 3.489, y: -0.749, z: -0.749 },
        { element: 'C', x: 2.789, y: -2.427, z: -0.749 },
        { element: 'C', x: 1.213, y: -3.489, z: -0.749 },
        { element: 'C', x: -1.213, y: -3.489, z: -0.749 },
        { element: 'C', x: -2.789, y: -2.427, z: -0.749 },
        { element: 'C', x: -3.489, y: -0.749, z: -0.749 },
        { element: 'C', x: -3.489, y: 1.213, z: -0.749 },
        { element: 'C', x: -2.789, y: 2.427, z: -0.749 },
        { element: 'C', x: -1.213, y: 3.489, z: -0.749 },
        { element: 'C', x: 1.213, y: 3.489, z: -0.749 },
        { element: 'C', x: 2.789, y: 2.427, z: -0.749 },
      ],
    },
  },
  {
    name: 'DNA Fragment',
    description: 'Short DNA double-helix segment (simplified)',
    tags: ['nucleic acid', 'biomolecule'],
    data: {
      atoms: [
        { element: 'P', x: -2.500, y: -4.000, z: 0.000 },
        { element: 'O', x: -1.500, y: -3.500, z: 0.800 },
        { element: 'O', x: -3.500, y: -3.500, z: -0.800 },
        { element: 'O', x: -2.500, y: -5.300, z: 0.500 },
        { element: 'O', x: -2.000, y: -3.500, z: -1.200 },
        { element: 'C', x: -0.800, y: -2.800, z: 0.500 },
        { element: 'C', x: 0.200, y: -3.400, z: 1.400 },
        { element: 'O', x: 1.400, y: -2.700, z: 1.100 },
        { element: 'C', x: 0.600, y: -4.800, z: 1.100 },
        { element: 'C', x: -0.200, y: -5.600, z: 2.100 },
        { element: 'O', x: 0.400, y: -5.800, z: 3.200 },
        { element: 'N', x: -1.400, y: -6.200, z: 1.800 },
        { element: 'C', x: -2.200, y: -6.000, z: 0.700 },
        { element: 'N', x: -3.300, y: -6.600, z: 0.800 },
        { element: 'C', x: -3.200, y: -7.200, z: 2.000 },
        { element: 'N', x: -2.100, y: -6.900, z: 2.700 },
        { element: 'C', x: 2.200, y: -6.200, z: 0.700 },
        { element: 'N', x: 3.300, y: -6.600, z: 0.800 },
        { element: 'C', x: 3.200, y: -7.200, z: 2.000 },
        { element: 'N', x: 2.100, y: -6.900, z: 2.700 },
        { element: 'C', x: 1.400, y: -5.800, z: 1.800 },
        { element: 'C', x: -0.600, y: -2.800, z: -0.800 },
        { element: 'O', x: -1.400, y: -2.200, z: -1.500 },
        { element: 'P', x: 2.500, y: -4.000, z: 0.000 },
        { element: 'O', x: 1.500, y: -3.500, z: 0.800 },
        { element: 'O', x: 3.500, y: -3.500, z: -0.800 },
        { element: 'O', x: 2.500, y: -5.300, z: 0.500 },
        { element: 'H', x: -0.400, y: -1.900, z: 0.900 },
        { element: 'H', x: -0.200, y: -3.300, z: 2.400 },
        { element: 'H', x: 1.400, y: -4.700, z: 0.400 },
        { element: 'H', x: 0.800, y: -5.300, z: 0.200 },
        { element: 'H', x: -4.000, y: -7.700, z: 2.400 },
        { element: 'H', x: -1.700, y: -7.300, z: 3.500 },
        { element: 'H', x: 4.000, y: -7.700, z: 2.400 },
        { element: 'H', x: 1.700, y: -7.300, z: 3.500 },
        { element: 'H', x: 2.400, y: -5.500, z: 2.400 },
        { element: 'H', x: -0.200, y: -3.400, z: -1.400 },
      ],
    },
  },
];
